// lib/services.ts
export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  category: string;
  overview: string;
  whatToExpect: string[];
  whenToSeeDoctor: string[];
  whyChooseDrSanjana: string[];
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
  metaTitle: string;
  metaDescription: string;
}

export const services: Service[] = [
  {
    slug: 'pregnancy-care',
    title: 'Pregnancy Care in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Pregnancy Care',
    description: 'Comprehensive prenatal support from conception to delivery.',
    icon: 'Baby',
    category: 'Obstetrics',
    overview: 'Pregnancy is one of the most beautiful journeys of your life, and you deserve expert, compassionate care every step of the way. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), Dr. Sanjana L provides comprehensive pregnancy care tailored to your unique needs — from your first prenatal visit through safe delivery and beyond. With 10 plus years of experience managing both routine and complex pregnancies, Dr. Sanjana ensures you feel informed, supported, and confident throughout your journey to motherhood.',
    whatToExpect: [
      'Initial consultation and dating scan in the first trimester',
      'Regular prenatal check-ups every 4 weeks (adjusting closer to delivery)',
      'Blood tests, anomaly scans, and glucose tolerance screening',
      'Nutrition guidance, weight monitoring, and exercise advice',
      'Birth planning discussion and delivery preparation',
      'Postpartum follow-up and breastfeeding support',
    ],
    whenToSeeDoctor: [
      'As soon as you suspect you are pregnant',
      'If you experience heavy bleeding, severe cramps, or unusual discharge',
      'Reduced fetal movements after 28 weeks',
      'Severe headache, blurred vision, or swollen hands/feet',
      'Any concerns about your baby\'s growth or wellbeing',
    ],
    whyChooseDrSanjana: [
      '10 plus years managing both routine and high-risk pregnancies',
      'Multilingual consultations (English, Hindi, Kannada, Telugu)',
      'Personalised birth plans and patient-centred approach',
      'Seamless coordination with the delivery team for your comfort',
    ],
    faqs: [
      { q: 'When should I book my first prenatal appointment?', a: 'Ideally book your first appointment as soon as you get a positive pregnancy test, typically between 6–8 weeks of pregnancy. Early visits help confirm healthy fetal development and establish your care plan.' },
      { q: 'How many prenatal visits are recommended?', a: 'A standard pregnancy involves about 10–12 prenatal visits. These are more frequent early on and as your due date approaches. High-risk pregnancies may require additional monitoring.' },
      { q: 'Does Dr. Sanjana deliver babies?', a: 'Yes, Dr. Sanjana L manages deliveries at both Health Nest (HSR Layout) and Raghava Hospital (Attibele) and will guide you through your birth plan, whether you are aiming for a normal vaginal delivery or a planned caesarean section.' },
    ],
    relatedSlugs: ['high-risk-pregnancy', 'normal-delivery', 'painless-delivery', 'prenatal-screening'],
    metaTitle: 'Pregnancy Care in HSR Layout & Attibele Bangalore | Dr. Sanjana L',
    metaDescription: 'Comprehensive pregnancy care at Health Nest (HSR Layout) and Raghava Hospital (Attibele). Dr. Sanjana L provides prenatal check-ups, ultrasound guidance & safe deliveries.',
  },
  {
    slug: 'high-risk-pregnancy',
    title: 'High Risk Pregnancy Specialist in HSR Layout & Attibele',
    shortTitle: 'High-Risk Pregnancy',
    description: 'Expert management for gestational diabetes, preeclampsia, and complex pregnancies.',
    icon: 'HeartPulse',
    category: 'Obstetrics',
    overview: 'A high-risk pregnancy requires a higher level of monitoring, expertise, and compassionate care. Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele) specialises in managing conditions such as gestational diabetes, preeclampsia, multiple pregnancies, advanced maternal age, and prior pregnancy complications. With state-of-the-art diagnostic tools and a patient-centred philosophy, Dr. Sanjana ensures that both you and your baby receive the vigilant attention necessary for the best possible outcome.',
    whatToExpect: [
      'Detailed risk assessment and personalised monitoring plan',
      'Frequent ultrasounds and fetal well-being tests',
      'Specialist coordination for conditions like diabetes or cardiac issues',
      'Growth scans (every 2–4 weeks) to monitor fetal development',
      'Daily kick count guidance and warning sign education',
      'Planned delivery timing and mode based on your specific condition',
    ],
    whenToSeeDoctor: [
      'Diagnosis of gestational diabetes or pre-existing diabetes',
      'History of preeclampsia, preterm birth, or pregnancy loss',
      'Carrying twins, triplets, or higher-order multiples',
      'Advanced maternal age (35+ years)',
      'Chronic conditions like hypertension, thyroid disorders, or autoimmune diseases',
    ],
    whyChooseDrSanjana: [
      'Extensive experience in managing complex, high-risk pregnancies',
      'Close coordination with specialists in South Bangalore and Attibele',
      'Evidence-based protocols for best maternal and fetal outcomes',
      'Compassionate, anxiety-reducing communication throughout your pregnancy',
    ],
    faqs: [
      { q: 'What qualifies a pregnancy as high-risk?', a: 'A pregnancy is considered high-risk when there are conditions that could affect the health of the mother, baby, or both. Common reasons include gestational diabetes, hypertension, multiple pregnancies, advanced maternal age, and previous complicated deliveries.' },
      { q: 'Can a high-risk pregnancy result in a normal delivery?', a: 'Yes, many women with high-risk pregnancies go on to have safe vaginal deliveries. The mode of delivery depends on your specific case and will be decided collaboratively with Dr. Sanjana as your due date approaches.' },
    ],
    relatedSlugs: ['pregnancy-care', 'normal-delivery', 'cesarean-delivery', 'prenatal-screening'],
    metaTitle: 'High Risk Pregnancy Specialist in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Expert high-risk pregnancy management by Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele). Specialist in gestational diabetes & more.',
  },
  {
    slug: 'normal-delivery',
    title: 'Normal Delivery Doctor in HSR Layout, Attibele & South Bangalore',
    shortTitle: 'Normal Delivery',
    description: 'Safe, evidence-based vaginal delivery care with experienced obstetric guidance — at Health Nest (HSR Layout) and Raghava Hospital (Attibele).',
    icon: 'Smile',
    category: 'Obstetrics',
    overview: 'A natural, vaginal delivery is often the most beneficial outcome for both mother and baby — with faster recovery, lower complication rates, and stronger early bonding. As a trusted normal delivery doctor in HSR Layout and a leading normal delivery doctor in Attibele, Dr. Sanjana L supports and encourages vaginal birth for eligible women, providing expert antenatal preparation, continuous labour support, and evidence-based pain management.\n\nDr. Sanjana practises at Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), serving women from HSR Layout, Sarjapura Road, Electronic City, Koramangala, BTM Layout, Bellandur, Bommanahalli, Chandapura, Hosur Road and across South Bangalore. As a normal delivery doctor in South Bangalore with over 10 years of obstetric experience, she has supported thousands of safe vaginal births — including for first-time mothers, vaginal birth after caesarean (VBAC) candidates and women with previous high-risk pregnancies.\n\nThe best hospital for normal delivery in HSR Layout or the best hospital for normal delivery in Attibele is the one that combines a low-intervention philosophy with full emergency back-up — and that is exactly what Health Nest and Raghava Hospital are equipped to offer. Both are 24/7 maternity-ready with paediatric, anaesthesia and operative theatre support if labour ever needs to switch course.',
    whatToExpect: [
      'Birth planning consultation by week 32–34 — discussing preferences, fears, pain relief and birth partner role',
      'Continuous labour monitoring with cardiotocography (CTG) for fetal wellbeing',
      'Access to all evidence-based pain relief options — breathing, positioning, warm compresses, hydrotherapy and painless delivery (epidural)',
      'Active pushing support and perineal protection techniques to reduce tears',
      'Immediate skin-to-skin contact, delayed cord clamping and early breastfeeding initiation',
      'Postnatal monitoring, lactation support and a structured 6-week recovery plan',
      'Shorter hospital stay (typically 24–48 hours) and faster return to normal activity',
    ],
    whenToSeeDoctor: [
      'Regular uterine contractions increasing in frequency and intensity (every 5 minutes for 1 hour, term pregnancy)',
      'Water breaking (rupture of membranes) — clear or pink fluid leak',
      'Decrease in fetal movements near term — fewer than 10 movements in 2 hours',
      'Any bleeding or unusual discharge in late pregnancy',
      'Severe headache, blurred vision or upper abdominal pain (possible preeclampsia)',
      'Persistent backache or pelvic pressure that feels different from usual',
    ],
    whyChooseDrSanjana: [
      '10+ years of obstetric experience — strong track record of safe, low-intervention normal deliveries',
      'Multilingual care (English, Hindi, Kannada, Telugu) for clear birth planning',
      'Patient-led birth planning with informed consent at every step',
      'Both clinic locations are 24/7 maternity-ready with anaesthesia, paediatric and operative back-up',
      'Experienced in managing shoulder dystocia, prolonged labour, and other vaginal birth complications',
      'Flexible birth choices — VBAC, painless delivery (epidural), or unmedicated vaginal birth as you prefer',
      'Transparent communication about normal delivery cost in HSR Layout and Attibele — no hidden charges',
    ],
    faqs: [
      { q: 'Is normal delivery better than caesarean?', a: 'For most women without medical contraindications, normal (vaginal) delivery offers faster recovery (return to activity in 1–2 weeks vs 4–6 weeks), lower risk of infection and bleeding, easier breastfeeding initiation, and lifelong benefits for the baby such as exposure to maternal microbiome. However, the best option depends on your individual health, baby position, and pregnancy course. Dr. Sanjana — your normal delivery doctor in HSR Layout and Attibele — will guide you based on your medical evaluation.' },
      { q: 'What pain relief options are available during labour at Health Nest and Raghava Hospital?', a: 'Multiple options are available: breathing techniques, position changes, warm compresses, hydrotherapy, nitrous oxide (laughing gas), IV opioids and epidural anaesthesia (painless delivery). Dr. Sanjana discusses every option during your birth planning session and ensures pain relief matches your preference.' },
      { q: 'How much does normal delivery cost in HSR Layout?', a: 'The normal delivery cost in HSR Layout typically ranges between INR 60,000 and INR 1,20,000 at Health Nest, depending on room category (general, semi-private, private), length of stay and any additional procedures (epidural, neonatal observation). Most major health insurance policies provide cashless cover. Call the clinic for the latest package.' },
      { q: 'How much does normal delivery cost in Attibele?', a: 'The normal delivery cost in Attibele at Raghava Multispeciality Hospital typically ranges between INR 45,000 and INR 90,000 — slightly more affordable than central Bangalore options. Insurance cashless support is available. Confirm exact pricing with the front desk before admission.' },
      { q: 'Am I eligible for a normal delivery?', a: 'Most healthy women with a single, head-down baby and no medical contraindications are good candidates. Conditions that may require a planned caesarean instead include placenta previa, breech or transverse presentation, certain previous uterine surgeries, severe preeclampsia or active genital infections. Dr. Sanjana evaluates your eligibility at every antenatal visit and reviews your final birth plan around 36 weeks.' },
      { q: 'What is VBAC and is it offered in HSR Layout or Attibele?', a: 'VBAC stands for Vaginal Birth After Caesarean. Many women with a previous low-transverse caesarean section can safely deliver vaginally in subsequent pregnancies. Dr. Sanjana supports VBAC at Health Nest (HSR Layout) and Raghava Hospital (Attibele) when criteria are met — single baby, head-down, no other contraindications, and full emergency back-up available.' },
      { q: 'Is the best hospital for normal delivery in Sarjapura Road close by?', a: 'Health Nest (1162, 24th Main Road, Sector 2, HSR Layout) is approximately 15 minutes from Sarjapura Road and is a popular choice as the best hospital for normal delivery near Sarjapura Road. For families closer to Hosur Road, Chandapura, Anekal or Jigani, Raghava Multispeciality Hospital (Attibele) offers full maternity facilities at a similar standard.' },
      { q: 'How can I prepare for a normal delivery?', a: 'Start prenatal yoga from the second trimester, walk daily, practise pelvic floor exercises, attend childbirth education sessions, eat a balanced antenatal diet and keep weight gain in target range. Read Dr. Sanjana\'s detailed blog: how to prepare for normal delivery (15 evidence-based tips).' },
      { q: 'What if my normal delivery has to switch to a caesarean section?', a: 'Both Health Nest and Raghava Hospital are operative-theatre ready 24/7. If complications arise during labour — fetal distress, failure to progress, cord prolapse — Dr. Sanjana and the anaesthesia team are equipped to perform a safe, prompt caesarean section under epidural or general anaesthesia.' },
      { q: 'Can I have a birth partner present during normal delivery?', a: 'Yes. Both Health Nest (HSR Layout) and Raghava Hospital (Attibele) welcome a birth partner — usually the spouse or mother — during labour and delivery, in line with current hospital policy. Confirm at your 36-week visit.' },
    ],
    relatedSlugs: ['painless-delivery', 'pregnancy-care', 'cesarean-delivery', 'high-risk-pregnancy'],
    metaTitle: 'Normal Delivery Doctor in HSR Layout, Attibele & South Bangalore | Dr. Sanjana L',
    metaDescription: 'Best normal delivery doctor in HSR Layout, Attibele & South Bangalore. Dr. Sanjana L offers safe vaginal birth, VBAC, painless delivery options at Health Nest and Raghava Hospital. Transparent normal delivery cost.',
  },
  {
    slug: 'painless-delivery',
    title: 'Painless Delivery in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Painless Delivery',
    description: 'Comfortable, pain-managed labour and delivery using modern epidural anaesthesia techniques.',
    icon: 'HeartHandshake',
    category: 'Obstetrics',
    overview: `Painless delivery (epidural or labour analgesia) is a safe way to reduce labour pain. Dr. Sanjana L offers it at Health Nest (HSR Layout) and Raghava Hospital (Attibele) when you are a good fit for the procedure.

An epidural is regional anaesthesia. A trained anaesthetist places it in your lower back during active labour. You stay awake. Many women feel pressure from contractions but not sharp pain. You can usually push when it is time, and hold your baby soon after birth.

Dr. Sanjana will explain natural coping methods, partial pain relief, and full epidural options in birth planning. Together you choose a plan that matches your wishes and your health. The aim is a safe birth and a calm, supported experience.`,
    whatToExpect: [
      'Birth planning visit: discuss epidural, breathing techniques, and other comfort options.',
      'On delivery day: the anaesthetist places a thin catheter in your lower back (often 10–15 minutes) while you sit or lie on your side.',
      'Relief often starts within 10–20 minutes. You may feel pressure but less sharp pain with contractions.',
      'Your vitals, your baby\'s heart rate, and labour progress are monitored throughout.',
      'You stay awake and push when your cervix is fully dilated, unless your team advises otherwise.',
      'Skin-to-skin and early breastfeeding are encouraged when medically appropriate.',
      'After birth: monitoring, recovery support, and removal of the epidural catheter.',
    ],
    whenToSeeDoctor: [
      'You are pregnant and wish to discuss pain management options for your upcoming delivery',
      'You had a previous traumatic or very painful delivery and want a more comfortable experience this time',
      'You have a low pain threshold and are anxious about labour pain',
      'You are in active labour and your contractions are becoming increasingly painful and difficult to manage',
      'You have been advised bed rest or have a medical condition where reducing stress during labour is beneficial',
    ],
    whyChooseDrSanjana: [
      'Experienced in managing both natural and epidural-assisted deliveries with equal expertise',
      'Works with trained anaesthetists who specialise in obstetric epidurals at both HSR Layout and Attibele',
      'Patient-centred approach — your birth plan and preferences are always respected',
      'Continuous monitoring throughout labour ensures safety for both mother and baby',
      'Available at two locations: Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele)',
      'Multilingual consultations in English, Hindi, Kannada, and Telugu for complete comfort and understanding',
    ],
    faqs: [
      { q: 'What is painless delivery and how does it work?', a: 'Painless delivery uses epidural anaesthesia — a form of regional pain relief administered through a thin catheter placed in the lower back by an anaesthetist. It blocks pain signals from the lower body while keeping you fully conscious and able to push during delivery. The effect begins within 10–20 minutes and can be adjusted throughout labour.' },
      { q: 'Is painless delivery (epidural) safe for the baby?', a: 'Yes. Epidural anaesthesia is one of the most well-studied and widely used pain relief methods in obstetrics worldwide. The medication acts locally and only a very small amount reaches the baby. Decades of research and clinical practice confirm it is safe for both mother and baby when administered by a qualified anaesthetist.' },
      { q: 'Who is eligible for painless delivery?', a: 'Most women with uncomplicated pregnancies at term (37 weeks or more) are eligible for epidural delivery. Dr. Sanjana will evaluate your medical history, any spinal conditions, blood clotting status, and overall health to confirm eligibility during your prenatal visits.' },
      { q: 'Does the epidural slow down labour or increase the chance of C-section?', a: 'Modern low-dose epidurals do not significantly slow down labour or increase C-section rates. In fact, by reducing pain and anxiety, many women are able to relax and progress through labour more smoothly. Dr. Sanjana monitors your labour closely and adjusts the plan as needed.' },
      { q: 'What is the cost of painless delivery in HSR Layout and Attibele?', a: 'The cost of painless delivery varies depending on the facility and the duration of labour. Please call Health Nest (+91-9449031003) or Raghava Hospital (+91-9980031006) for the latest fee information. Our team will provide a detailed cost estimate during your prenatal consultation.' },
      { q: 'Can I choose painless delivery during labour or do I need to decide in advance?', a: 'While it is best to discuss your preference during prenatal visits so the team can prepare, an epidural can also be given during active labour if you change your mind. However, there is a point in advanced labour beyond which an epidural may no longer be effective, so early discussion is recommended.' },
      { q: 'What are the side effects of epidural anaesthesia?', a: 'Common side effects include temporary numbness in the legs, a mild drop in blood pressure (managed with IV fluids), and occasionally a headache. Serious complications are extremely rare. Dr. Sanjana and the anaesthetist will explain all risks and benefits before the procedure.' },
      { q: 'Can I breastfeed immediately after a painless delivery?', a: 'Yes. Since the epidural keeps you fully conscious and alert, you can hold your baby and initiate breastfeeding immediately after delivery — just as you would after a natural delivery without pain relief.' },
    ],
    relatedSlugs: ['normal-delivery', 'pregnancy-care', 'high-risk-pregnancy', 'cesarean-delivery'],
    metaTitle: 'Painless Delivery in HSR Layout & Attibele Bangalore | Dr. Sanjana L',
    metaDescription: 'Comfortable, pain-free delivery with epidural anaesthesia at Health Nest (HSR Layout) and Raghava Hospital (Attibele). Dr. Sanjana L offers safe painless normal delivery with expert care.',
  },
  {
    slug: 'cesarean-delivery',
    title: 'Caesarean Delivery (C-Section) in HSR Layout & Attibele',
    shortTitle: 'Caesarean Delivery',
    description: 'Safe, skilled caesarean sections when medically indicated or planned.',
    icon: 'Stethoscope',
    category: 'Obstetrics',
    overview: 'When a normal vaginal delivery is not possible or poses risks to mother or baby, a caesarean section (C-section) is a life-saving surgical intervention performed by Dr. Sanjana L with exceptional skill and care. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), she ensures the procedure is carried out safely, with clear communication, minimal discomfort, and a focus on quick recovery.',
    whatToExpect: [
      'Pre-operative consultation explaining the procedure fully',
      'Anaesthesia discussion (spinal or general)',
      'Surgical incision and delivery — typically within 10 minutes',
      'Immediate newborn assessment and early breastfeeding support',
      'Post-operative pain management and wound care',
      'Recovery guidance and follow-up appointments',
    ],
    whenToSeeDoctor: [
      'Previous caesarean delivery (VBAC may be possible — discuss options)',
      'Breech or transverse baby position near term',
      'Placenta previa or accreta',
      'Twin pregnancies with complex positions',
      'Foetal distress during labour',
    ],
    whyChooseDrSanjana: [
      'Extensive surgical experience in both elective and emergency C-sections',
      'Gentle surgical technique minimising recovery time',
      'Clear pre-operative counselling and post-op support',
      'Experience with VBAC counselling for women with prior C-sections',
    ],
    faqs: [
      { q: 'Is recovery from C-section painful?', a: 'Discomfort is expected but well-managed with appropriate pain relief. Most women are up and walking within 24 hours. Full recovery typically takes 4–6 weeks, and Dr. Sanjana provides detailed aftercare instructions.' },
      { q: 'Can I have a normal delivery after a C-section?', a: 'Yes, in many cases a Vaginal Birth After Caesarean (VBAC) is possible. Dr. Sanjana will assess your specific situation and discuss the risks and benefits with you.' },
    ],
    relatedSlugs: ['normal-delivery', 'pregnancy-care', 'high-risk-pregnancy', 'postnatal-care'],
    metaTitle: 'C-Section Delivery in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Safe and skilled caesarean section surgery by Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele). Expert planned and emergency C-section care.',
  },
  {
    slug: 'fertility-treatment',
    title: 'Fertility Treatment in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Fertility Treatment',
    description: 'Comprehensive fertility evaluation and treatment to help you conceive.',
    icon: 'Flower2',
    category: 'Fertility',
    overview: 'Struggling to conceive can be an emotionally challenging experience. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), Dr. Sanjana L offers compassionate, evidence-based fertility evaluation and treatment, helping couples understand the root cause of their difficulty and offering a clear path forward. From basic investigations to advanced treatments like IUI and IVF referral, every step is taken with sensitivity and personalised care.',
    whatToExpect: [
      'Detailed fertility consultation for both partners',
      'Hormonal blood tests (FSH, LH, AMH, thyroid)',
      'Semen analysis and male factor evaluation',
      'Pelvic ultrasound to assess ovarian reserve and uterine health',
      'Ovulation tracking and induction cycles if needed',
      'IUI (Intrauterine Insemination) support',
      'IVF referral and co-management with fertility specialists',
    ],
    whenToSeeDoctor: [
      'Trying to conceive for 12+ months (under 35) or 6+ months (over 35)',
      'Irregular or absent periods',
      'Prior diagnosis of PCOS, endometriosis, or fibroids',
      'History of recurrent miscarriages',
      'Male partner with known fertility issues',
    ],
    whyChooseDrSanjana: [
      'Empathetic, non-judgmental approach to fertility challenges',
      'Comprehensive investigations to identify root causes',
      'Experience with ovulation induction and IUI procedures',
      'Trusted referral network for IVF and ART specialists in Bangalore',
    ],
    faqs: [
      { q: 'When should a couple seek fertility help?', a: 'If you are under 35 and have been trying to conceive for 12 months without success, or over 35 and trying for 6 months, it is a good time to seek evaluation. Women with known conditions like PCOS or endometriosis can seek help earlier.' },
      { q: 'What is IUI?', a: 'Intrauterine Insemination (IUI) is a fertility procedure where processed sperm is placed directly into the uterus around ovulation. It is less invasive than IVF and is often a first-line treatment for certain types of infertility.' },
    ],
    relatedSlugs: ['ivf-iui', 'pcos-pcod-treatment', 'menstrual-disorders', 'pregnancy-care'],
    metaTitle: 'Fertility Treatment in HSR Layout & Attibele Bangalore',
    metaDescription: 'Struggling to conceive? Dr. Sanjana L offers fertility evaluation, IUI & IVF counselling at Health Nest (HSR Layout) and Raghava Hospital (Attibele).',
  },
  {
    slug: 'ivf-iui',
    title: 'IVF & IUI Treatment in HSR Layout & Attibele | Bangalore',
    shortTitle: 'IVF & IUI',
    description: 'Advanced assisted reproductive technology for couples facing infertility.',
    icon: 'Microscope',
    category: 'Fertility',
    overview: 'When natural conception and simpler fertility treatments have not been successful, assisted reproductive technologies (ART) like IUI and IVF can significantly improve your chances of conception. Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele) guides couples through these procedures with expert medical management, emotional support, and trusted referrals to specialised ART centres when required.',
    whatToExpect: [
      'Thorough pre-ART evaluation and counselling',
      'IUI: Ovarian stimulation, monitoring scans, and insemination',
      'IVF: Co-management with your IVF centre — egg retrieval, fertilisation, embryo transfer',
      'Luteal phase support and early pregnancy monitoring',
      'Hormonal support and follow-up throughout treatment cycles',
    ],
    whenToSeeDoctor: [
      'Failed IUI cycles (typically 3–4 attempts)',
      'Severely compromised sperm parameters',
      'Tubal factor infertility',
      'Advanced maternal age with diminished ovarian reserve',
      'Recurrent implantation failure',
    ],
    whyChooseDrSanjana: [
      'Experience in IUI procedures with high success orientation',
      'Coordination with top IVF labs in Bangalore and Hosur area',
      'Supportive counselling throughout emotionally demanding cycles',
      'Clear explanation of costs, timelines, and realistic expectations',
    ],
    faqs: [
      { q: 'What is the success rate of IVF?', a: 'IVF success rates vary based on age, diagnosis, and clinic. Generally, rates are 40–50% per cycle for women under 35, declining with age. Dr. Sanjana will give you a realistic expectation based on your individual profile.' },
      { q: 'How many IUI cycles should I try before moving to IVF?', a: 'Typically 3–4 IUI cycles are recommended before considering IVF, though this depends on your age, diagnosis, and how you are responding to treatment.' },
    ],
    relatedSlugs: ['fertility-treatment', 'pcos-pcod-treatment', 'menstrual-disorders', 'pregnancy-care'],
    metaTitle: 'IVF IUI Fertility Treatment in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Expert IUI and IVF guidance by Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele). Compassionate care for couples in South Bangalore.',
  },
  {
    slug: 'laparoscopic-surgery',
    title: 'Laparoscopic Surgery in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Laparoscopic Surgery',
    description: 'Minimally invasive surgery for fibroids, cysts, endometriosis, and more.',
    icon: 'Scissors',
    category: 'Surgery',
    overview: 'Laparoscopic (keyhole) surgery is a minimally invasive surgical approach that allows Dr. Sanjana L to diagnose and treat a wide range of gynaecological conditions through tiny incisions. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), she offers laparoscopy which means less pain, faster recovery, minimal scarring, and a quicker return to normal life. Dr. Sanjana is highly experienced in procedures for conditions including ovarian cysts, fibroids, endometriosis, and more.',
    whatToExpect: [
      'Pre-operative consultation and investigations',
      'Anaesthesia (general anaesthesia) — procedure typically done as day surgery',
      'Small incisions (5–10mm) through which a camera and instruments are inserted',
      'Procedure time: 30 minutes to 2 hours depending on complexity',
      'Recovery in hospital: usually 1 day',
      'Return to normal activities: 1–2 weeks',
    ],
    whenToSeeDoctor: [
      'Persistent pelvic pain not responding to medication',
      'Suspected ovarian cysts or fibroids',
      'Diagnosis or treatment of endometriosis',
      'Blocked fallopian tubes affecting fertility',
      'Undiagnosed pelvic or abdominal pathology',
    ],
    whyChooseDrSanjana: [
      'Extensive experience in advanced laparoscopic gynaecological surgery',
      'Minimal scarring and fast recovery techniques',
      'Clear pre- and post-operative counselling',
      'High surgical precision with availability at HSR and Attibele',
    ],
    faqs: [
      { q: 'Is laparoscopic surgery safe?', a: 'Yes, laparoscopic surgery is generally very safe with a low complication rate compared to open surgery. Dr. Sanjana will discuss specific risks based on your procedure during your pre-operative consultation.' },
      { q: 'How long is recovery after laparoscopic surgery?', a: 'Most patients return to light activity within 3–5 days and full activity within 1–2 weeks. This is significantly faster than open surgery, which typically requires 4–6 weeks.' },
    ],
    relatedSlugs: ['uterine-fibroids-treatment', 'hysterectomy', 'ovarian-cyst-treatment', 'endometriosis-treatment'],
    metaTitle: 'Laparoscopic Gynaecology Surgery in HSR Layout & Attibele',
    metaDescription: 'Minimally invasive laparoscopic surgery by Dr. Sanjana L at Health Nest and Raghava Hospital. Expert care for fibroids, cysts & endometriosis.',
  },
  {
    slug: 'hysteroscopy',
    title: 'Hysteroscopy in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Hysteroscopy',
    description: 'Diagnostic and operative hysteroscopy for uterine conditions.',
    icon: 'Search',
    category: 'Surgery',
    overview: 'Hysteroscopy is a procedure that allows Dr. Sanjana L to look inside the uterus using a thin, lighted telescope (hysteroscope) inserted through the cervix. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), it can be used for diagnosis (to investigate abnormal bleeding, recurrent miscarriage, or infertility) or for treatment. It is minimally invasive, usually requires no incisions, and offers rapid recovery.',
    whatToExpect: [
      'Pre-procedure consultation and investigation',
      'Usually performed under local or general anaesthesia',
      'Procedure time: 15–45 minutes',
      'No external incisions — scope is inserted through the vagina',
      'Mild cramping post-procedure, resolving within 1–2 days',
      'Return to normal activities within 1–3 days',
    ],
    whenToSeeDoctor: [
      'Abnormal or heavy menstrual bleeding',
      'Suspected uterine polyps or submucosal fibroids',
      'Recurrent implantation failure after IVF',
      'Recurrent miscarriages',
      'Suspected uterine septum or abnormality',
    ],
    whyChooseDrSanjana: [
      'Experience in both diagnostic and operative hysteroscopy',
      'Comfortable, well-explained procedure with minimal discomfort',
      'Expert uterine health assessment at both clinic hubs',
      'Detailed post-procedure report and next steps guidance',
    ],
    faqs: [
      { q: 'Is hysteroscopy painful?', a: 'Most women experience mild cramping similar to period pain during or after the procedure. Adequate anaesthesia is used to minimise discomfort. Dr. Sanjana will explain all pain management options before the procedure.' },
      { q: 'How long after hysteroscopy can I become pregnant?', a: 'After an operative hysteroscopy (e.g., polyp or septum removal), most doctors recommend waiting 1–3 months before trying to conceive to allow the uterus to heal properly.' },
    ],
    relatedSlugs: ['laparoscopic-surgery', 'fertility-treatment', 'menstrual-disorders', 'ivf-iui'],
    metaTitle: 'Hysteroscopy in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Diagnostic and operative hysteroscopy by Dr. Sanjana L at Health Nest and Raghava Hospital. Expert investigation for abnormal bleeding & infertility.',
  },
  {
    slug: 'pcos-pcod-treatment',
    title: 'PCOS Specialist & PCOD Doctor in HSR Layout, Attibele & South Bangalore',
    shortTitle: 'PCOS & PCOD Treatment',
    description: 'Evidence-based PCOS treatment in HSR Layout and PCOD treatment in Attibele — hormonal management, weight loss support, fertility care and adolescent PCOS treatment.',
    icon: 'Activity',
    category: 'Gynaecology',
    overview: 'Polycystic Ovary Syndrome (PCOS) and Polycystic Ovarian Disease (PCOD) are among the most common hormonal disorders in women of reproductive age — affecting roughly 1 in 5 Indian women. As a leading PCOS specialist in HSR Layout and an experienced PCOD doctor in Attibele, Dr. Sanjana L offers evidence-based diagnosis, hormonal management, fertility support and structured lifestyle counselling at Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele).\n\nWomen seeking PCOS treatment in HSR Layout, PCOS treatment in Attibele, PCOS treatment in Sarjapura, PCOS treatment in Electronic City, or hormonal imbalance treatment in HSR Layout and Attibele consult Dr. Sanjana for irregular cycles, weight gain, acne, hirsutism, hair fall and infertility. As a recognised PCOS specialist in South Bangalore, she serves patients from HSR Layout, Sarjapura Road, Koramangala, BTM Layout, Electronic City, Bellandur, Bommanahalli, Singasandra, Kudlu Gate, Chandapura and Hosur Road.\n\n**Adolescent and teenage PCOS care:** Dr. Sanjana also runs a dedicated PCOD in teenagers HSR Layout programme — early diagnosis in girls aged 12–19 dramatically reduces the risk of long-term metabolic, fertility and mental health issues. If your teenager has irregular periods, sudden weight gain, persistent acne or excessive hair growth, an early evaluation with a PCOS specialist in HSR Layout can change her trajectory.\n\nA full PCOS evaluation includes a hormonal panel, insulin resistance testing, pelvic ultrasound and a personalised treatment plan combining diet, exercise, supplements and (if indicated) medication. Read Dr. Sanjana\'s complete PCOS Diet Plan for Weight Loss with Indian foods and her PCOS vs PCOD differences guide for in-depth reading.',
    whatToExpect: [
      'Detailed hormonal and metabolic blood work — LH, FSH, testosterone, DHEAS, prolactin, insulin, HbA1c, lipid profile, vitamin D, AMH',
      'Thyroid panel (TSH, free T4) to rule out thyroid-related menstrual irregularities',
      'Pelvic ultrasound for ovarian morphology and uterine assessment',
      'Personalised treatment plan combining lifestyle, diet, supplements and medication',
      'Menstrual cycle regulation with appropriate hormonal therapy or insulin sensitisers',
      'Targeted weight loss support — addressing PCOS-driven insulin resistance',
      'Fertility support including ovulation induction, IUI guidance or IVF referral if desired',
      'Adolescent PCOS care — separate teenager-friendly clinics for girls 12–19',
      'Long-term follow-up to prevent type 2 diabetes, fatty liver and endometrial complications',
    ],
    whenToSeeDoctor: [
      'Irregular or absent periods (cycles longer than 35 days or fewer than 8 periods a year)',
      'Excessive hair growth on face, chest, back or abdomen (hirsutism)',
      'Hair thinning or female-pattern scalp hair loss',
      'Acne — especially on the jawline and chin — not responding to standard skincare',
      'Unexplained weight gain or difficulty losing weight despite diet and exercise',
      'Skin darkening in body folds (acanthosis nigricans) — an insulin-resistance marker',
      'Trouble conceiving after 6–12 months of trying',
      'Teenager with irregular periods, sudden weight gain or severe acne',
      'Mood swings, anxiety, low energy or sleep disturbance',
    ],
    whyChooseDrSanjana: [
      'Recognised PCOS specialist in HSR Layout and PCOD doctor in Attibele with 10+ years experience',
      'Holistic approach — hormonal, metabolic, nutritional and emotional support',
      'Integrated diet and lifestyle counselling — including Indian-food PCOS diet planning',
      'Adolescent-friendly clinic for PCOD in teenagers (HSR Layout & Attibele)',
      'Multilingual consultations — English, Hindi, Kannada, Telugu',
      'Convenient locations for patients from Sarjapura, Electronic City, Koramangala, BTM Layout, Bellandur and Hosur Road',
      'Long-term monitoring to protect against diabetes, cardiovascular disease and endometrial cancer',
      'Seamless referral to fertility services if conception support is needed',
    ],
    faqs: [
      { q: 'What is the difference between PCOS and PCOD?', a: 'PCOD is primarily an ovarian condition where the ovaries produce many immature eggs that become cystic — usually milder, often reversible with lifestyle. PCOS is a more complex systemic endocrine disorder with insulin resistance, higher androgens and long-term metabolic risks. PCOS is more severe, though both respond well to early, structured treatment with a PCOS specialist in HSR Layout or PCOD doctor in Attibele.' },
      { q: 'Can PCOS be cured?', a: 'PCOS cannot be permanently cured, but its symptoms can be very effectively managed and many of its consequences fully reversed. With sustained lifestyle change and appropriate medication, many women with PCOS conceive naturally, regulate their cycles, normalise their weight and live healthy lives.' },
      { q: 'Can a teenager have PCOS or PCOD?', a: 'Yes. PCOD in teenagers is increasingly common in HSR Layout, Sarjapura, Electronic City and across Bangalore — driven by sedentary screen time, refined-carb diets and sleep disruption. Diagnosis in adolescence is more nuanced (irregular cycles can be normal in the first 2 years after menarche), so Dr. Sanjana uses age-appropriate criteria. Early, sensitive intervention in teenagers protects future fertility and metabolic health.' },
      { q: 'What is the best diet for PCOS?', a: 'A low-glycaemic, high-protein, high-fibre Indian diet — built around millets, dals, vegetables, paneer, eggs, fish, nuts and seeds — is the most evidence-based PCOS diet. Refined carbs, sugar and ultra-processed foods worsen insulin resistance. Read Dr. Sanjana\'s complete 7-day PCOS Diet Plan for Weight Loss using Indian foods.' },
      { q: 'How long does PCOS treatment take to show results?', a: 'Most women see improvements in energy, bloating and acne within 4–6 weeks. Period regularity, meaningful weight loss and reduction in hirsutism typically take 3–6 months of consistent treatment. Reversal of insulin resistance is a 6–12 month process.' },
      { q: 'Will I need hormonal pills for PCOS treatment?', a: 'Not necessarily. Many women regulate their cycles and reverse symptoms with diet, exercise and inositol supplementation alone. Combined oral contraceptives, metformin or anti-androgens are added only when needed — Dr. Sanjana, your PCOS specialist in HSR Layout, makes this decision based on your individual hormonal panel and goals.' },
      { q: 'Can PCOS cause infertility?', a: 'PCOS can disrupt ovulation and is one of the most common causes of female subfertility. The good news: ovulation can be restored in most women with weight loss, inositol or letrozole. If first-line therapy fails, IUI or IVF guidance is available — see our fertility-treatment service for more.' },
      { q: 'How much does PCOS treatment cost in HSR Layout or Attibele?', a: 'A complete first-visit PCOS evaluation (consultation + hormonal panel + ultrasound) typically costs INR 4,000–8,000 depending on the test panel. Follow-up visits are more affordable. Insurance generally does not cover lifestyle clinics but does cover diagnostics and prescription medication. Call to confirm current pricing.' },
      { q: 'I am near Sarjapura Road / Electronic City — where do I get PCOS treatment?', a: 'Dr. Sanjana offers PCOS treatment in Sarjapura, PCOS treatment in Electronic City and as a PCOD specialist in Electronic City via her HSR Layout clinic (Health Nest, 1162, 24th Main Road, Sector 2 — about 15–20 minutes from Sarjapura Road and Electronic City). Patients in Attibele, Hosur Road, Chandapura or Anekal can consult at Raghava Multispeciality Hospital (Attibele).' },
      { q: 'Can I do an online PCOS consultation with Dr. Sanjana?', a: 'Yes — Dr. Sanjana offers online video consultations for PCOS follow-up, diet planning and prescription review. Initial diagnosis usually requires an in-person visit at Health Nest (HSR Layout) or Raghava Hospital (Attibele) for ultrasound and physical examination.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'fertility-treatment', 'adolescent-gynaecology', 'menopause-management'],
    metaTitle: 'PCOS Specialist HSR Layout & PCOD Doctor Attibele | Dr. Sanjana L',
    metaDescription: 'Trusted PCOS specialist in HSR Layout, PCOD doctor in Attibele. PCOS/PCOD treatment for adults and teenagers — hormonal evaluation, Indian diet plan, fertility support. Dr. Sanjana L at Health Nest and Raghava Hospital.',
  },
  {
    slug: 'menstrual-disorders',
    title: 'Menstrual Disorders Treatment in HSR Layout & Attibele',
    shortTitle: 'Menstrual Disorders',
    description: 'Diagnosis and treatment for irregular, painful, or heavy periods.',
    icon: 'Calendar',
    category: 'Gynaecology',
    overview: 'Menstrual irregularities — whether heavy bleeding, painful periods, absent periods, or irregular cycles — can significantly impact your quality of life. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), Dr. Sanjana L offers thorough evaluation and personalised treatment to restore comfortable, regular menstrual health.',
    whatToExpect: [
      'Detailed menstrual history and symptom assessment',
      'Blood tests (hormones, thyroid, anaemia screen)',
      'Pelvic ultrasound',
      'Hysteroscopy if abnormal uterine pathology is suspected',
      'Medical management with hormones, anti-inflammatories, or other medications',
      'Surgical management (hysteroscopy, laparoscopy) when required',
    ],
    whenToSeeDoctor: [
      'Periods lasting more than 7 days or saturating a pad every 1–2 hours',
      'Severe cramping that limits daily activities (dysmenorrhoea)',
      'No period for 3+ months (not due to pregnancy)',
      'Bleeding between periods or after intercourse',
      'Sudden changes in your normal menstrual pattern',
    ],
    whyChooseDrSanjana: [
      'Thorough evaluation to identify the root cause — not just manage symptoms',
      'Range of medical and surgical treatment options',
      'Expert care available in both HSR Layout and Attibele clinics',
      'Long-term follow-up to ensure lasting improvement',
    ],
    faqs: [
      { q: 'What causes heavy periods?', a: 'Heavy periods (menorrhagia) can be caused by fibroids, polyps, adenomyosis, hormonal imbalances, thyroid disorders, or clotting problems. A thorough evaluation by Dr. Sanjana will identify the cause and guide appropriate treatment.' },
      { q: 'Are painful periods normal?', a: 'Mild cramping during periods is common, but severe pain that interferes with your daily life is not normal and should be evaluated. Conditions like endometriosis or adenomyosis are common causes of severe period pain.' },
    ],
    relatedSlugs: ['pcos-pcod-treatment', 'laparoscopic-surgery', 'hysteroscopy', 'menopause-management'],
    metaTitle: 'Menstrual Disorders Treatment in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Diagnosis and treatment for irregular, heavy, or painful periods by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'menopause-management',
    title: 'Menopause Management in HSR Layout & Attibele',
    shortTitle: 'Menopause Management',
    description: 'Supportive care to help you navigate menopause comfortably and healthily.',
    icon: 'Sun',
    category: 'Gynaecology',
    overview: 'Menopause is a natural transition in every woman\'s life, but its symptoms can significantly affect your wellbeing. Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele) provides comprehensive menopause care, offering everything from symptom management to long-term health protection, helping you embrace this new chapter with confidence.',
    whatToExpect: [
      'Comprehensive menopausal assessment (symptoms, LMP, blood tests)',
      'Bone density assessment (DEXA scan referral if needed)',
      'Discussion of Hormone Replacement Therapy (HRT) — risks and benefits',
      'Non-hormonal alternatives for symptom management',
      'Cardiovascular and bone health guidance',
      'Ongoing monitoring and medication adjustment if on HRT',
    ],
    whenToSeeDoctor: [
      'Hot flushes and night sweats disrupting your sleep and daily life',
      'Vaginal dryness or pain during intercourse',
      'Mood swings, anxiety, or depression around the menopausal transition',
      'Irregular periods in your 40s or 50s',
      'Concerns about bone health or osteoporosis risk',
    ],
    whyChooseDrSanjana: [
      'Evidence-based menopause care tailored to your profile',
      'Open, comfortable conversations about intimate health concerns',
      'Personalised care at HSR Layout & Attibele locations',
      'Long-term wellness focus beyond just symptom relief',
    ],
    faqs: [
      { q: 'What is the average age of menopause in Indian women?', a: 'The average age of natural menopause in Indian women is around 46–47 years, slightly earlier than the global average of 51. Perimenopause (the transition phase) can begin several years before this.' },
      { q: 'Is Hormone Replacement Therapy (HRT) safe?', a: 'For most women under 60 who start HRT within 10 years of menopause, the benefits generally outweigh the risks. Dr. Sanjana will review your complete health history to determine if HRT is appropriate and safe for you.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'cervical-cancer-screening', 'urogynaecology', 'contraception-counselling'],
    metaTitle: 'Menopause Management in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Compassionate menopause care including HRT and symptom management by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'prenatal-screening',
    title: 'Prenatal Screening in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Prenatal Screening',
    description: 'Comprehensive antenatal tests for healthy fetal development.',
    icon: 'ScanLine',
    category: 'Obstetrics',
    overview: 'Prenatal screening helps detect potential chromosomal abnormalities, structural defects, and maternal health risks early in pregnancy. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), Dr. Sanjana L guides you through all recommended screening tests with clear explanations, helping you make informed decisions without unnecessary anxiety.',
    whatToExpect: [
      'First trimester combined screening (nuchal translucency scan + blood tests)',
      'Non-Invasive Prenatal Testing (NIPT) for chromosomal conditions',
      'Anomaly scan (morphology scan) at 18–22 weeks',
      'Glucose Tolerance Test (GTT) for gestational diabetes',
      'Growth scans in the third trimester',
      'Biophysical profile and Doppler studies if indicated',
    ],
    whenToSeeDoctor: [
      'As part of your routine early pregnancy care',
      'Family history of chromosomal conditions',
      'Advanced maternal age (35+ years)',
      'Previous pregnancy with a chromosomal or structural abnormality',
    ],
    whyChooseDrSanjana: [
      'Thorough counselling before and after screening tests',
      'Clear explanation of test results at HSR and Attibele clinics',
      'Coordinated referral for further diagnostic tests if needed',
      'Supportive, non-directive approach to informed decision-making',
    ],
    faqs: [
      { q: 'Is prenatal screening mandatory?', a: 'Prenatal screening is not mandatory — it is your choice. Dr. Sanjana will explain each test, what it checks for, and what the results might mean, empowering you to decide what is right for you and your family.' },
      { q: 'What is the difference between screening and diagnostic tests?', a: 'Screening tests (like NIPT and anomaly scans) identify risks but are not definitive. If a screening test raises a concern, diagnostic tests like amniocentesis or chorionic villus sampling (CVS) can confirm the diagnosis.' },
    ],
    relatedSlugs: ['pregnancy-care', 'high-risk-pregnancy', 'postnatal-care', 'normal-delivery'],
    metaTitle: 'Prenatal Screening in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Comprehensive prenatal screening including anomaly scans, NIPT, and GTT guided by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'postnatal-care',
    title: 'Postnatal Care in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Postnatal Care',
    description: 'Post-delivery recovery, breastfeeding support, and newborn care guidance.',
    icon: 'Heart',
    category: 'Obstetrics',
    overview: 'The weeks after delivery are a time of physical recovery and emotional adjustment. Dr. Sanjana L provides comprehensive postnatal care at Health Nest (HSR Layout) and Raghava Hospital (Attibele) to support your healing, address breastfeeding challenges, and monitor your emotional wellbeing.',
    whatToExpect: [
      'Postnatal review at 1–2 weeks post-delivery (wound, recovery)',
      '6-week comprehensive postnatal check (physical and emotional)',
      'Breastfeeding counselling and lactation support',
      'Contraception counselling for the postnatal period',
      'Screening for postnatal depression and anxiety',
      'Pelvic floor and physical recovery guidance',
    ],
    whenToSeeDoctor: [
      'Heavy postpartum bleeding beyond the first 10 days',
      'Signs of wound infection (redness, swelling, discharge)',
      'Persistent perineal or caesarean wound pain',
      'Feeling overwhelmed, persistently sad, or anxious',
      'Difficulty breastfeeding or concerns about milk supply',
    ],
    whyChooseDrSanjana: [
      'Warm, comprehensive postnatal care at HSR Layout & Attibele',
      'Postnatal depression screening and compassionate mental health support',
      'Breastfeeding guidance with practical, evidence-based advice',
      'Long-term follow-up to ensure your full recovery',
    ],
    faqs: [
      { q: 'When should I have my first postnatal check?', a: 'Your first review should ideally happen 1–2 weeks after delivery to check your recovery, then a comprehensive 6-week check. If you had a C-section, wound review is particularly important at 1–2 weeks.' },
      { q: 'What is postnatal depression?', a: 'Postnatal depression is a type of depression that affects some new mothers after delivery. Symptoms include persistent sadness, anxiety, feeling overwhelmed, and difficulty bonding with your baby. Dr. Sanjana provides compassionate support at both clinical sites.' },
    ],
    relatedSlugs: ['pregnancy-care', 'normal-delivery', 'cesarean-delivery', 'prenatal-screening'],
    metaTitle: 'Postnatal Care in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Comprehensive postnatal care including recovery and breastfeeding support by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'contraception-counselling',
    title: 'Contraception Counselling in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Contraception Counselling',
    description: 'Personalised guidance on the right contraceptive method for your lifestyle.',
    icon: 'ShieldCheck',
    category: 'Gynaecology',
    overview: 'Choosing the right contraception is a deeply personal decision that depends on your health, lifestyle, and future plans. Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele) offers non-judgmental, comprehensive counselling on all available methods.',
    whatToExpect: [
      'Discussion of all contraceptive options: pills, patches, implant, IUD, injection, barrier methods',
      'Assessment of your health history and lifestyle to guide recommendations',
      'IUD (copper or hormonal) insertion if chosen',
      'Implant insertion if chosen',
      'Emergency contraception guidance',
      'Follow-up to review your chosen method and address any concerns',
    ],
    whenToSeeDoctor: [
      'Planning to delay or space pregnancies',
      'Unhappy with your current contraceptive method',
      'After delivery — planning postnatal contraception',
      'Perimenopausal contraception needs',
      'Questions about long-term contraceptive options',
    ],
    whyChooseDrSanjana: [
      'Non-judgmental, patient-led contraception counselling',
      'Experience with IUD and implant insertion procedures',
      'Expert guidance available at both Health Nest and Raghava Hospital',
      'Consideration of your complete health profile in recommendations',
    ],
    faqs: [
      { q: 'What is the most effective form of contraception?', a: 'Long-acting reversible contraceptives (LARCs) like hormonal IUDs (Mirena) and implants are the most effective (>99%). Oral contraceptive pills are 91–99% effective with typical use. Dr. Sanjana will help you find the best option for your lifestyle.' },
      { q: 'Is the copper IUD effective as emergency contraception?', a: 'Yes, the copper IUD is the most effective form of emergency contraception (>99%) when inserted within 5 days of unprotected intercourse, and provides ongoing long-term contraception.' },
    ],
    relatedSlugs: ['postnatal-care', 'menopause-management', 'adolescent-gynaecology', 'menstrual-disorders'],
    metaTitle: 'Contraception Counselling in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Expert, non-judgmental contraception counselling and IUD/implant insertion by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'cervical-cancer-screening',
    title: 'Cervical Cancer Screening in HSR Layout & Attibele',
    shortTitle: 'Cervical Cancer Screening',
    description: 'Pap smear and HPV testing for early detection and prevention.',
    icon: 'Shield',
    category: 'Gynaecology',
    overview: 'Cervical cancer is one of the most preventable cancers when detected early. At Health Nest (HSR Layout) and Raghava Hospital (Attibele), regular cervical screening identifies abnormal cells before they develop into cancer. Dr. Sanjana L provides comfortable, expert screening with clear follow-up guidance.',
    whatToExpect: [
      'Pap smear: a quick 2-minute procedure collecting cells from the cervix',
      'HPV testing: to detect high-risk HPV strains',
      'Results typically available within 1–2 weeks',
      'Colposcopy referral if abnormal results require further evaluation',
      'HPV vaccination guidance',
      'Screening reminder system to ensure regular follow-up',
    ],
    whenToSeeDoctor: [
      'All sexually active women from age 21 (or within 3 years of first intercourse)',
      'Bleeding after intercourse',
      'Unusual vaginal discharge',
      'Pelvic pain',
      'Due for routine 3-yearly screening',
    ],
    whyChooseDrSanjana: [
      'Comfortable, dignified screening experience at HSR and Attibele clinics',
      'Clear explanation of results and next steps',
      'Comprehensive screening combined with HPV testing',
      'Proactive HPV vaccination guidance',
    ],
    faqs: [
      { q: 'How often should women get a Pap smear?', a: 'Women aged 21–65 should have a Pap smear every 3 years. If combined with an HPV test (co-testing), screening can be every 5 years for women aged 30–65. Dr. Sanjana will recommend the schedule right for you.' },
      { q: 'Can I get a Pap smear during my period?', a: 'It is best to schedule your Pap smear when you are not menstruating, as blood can affect the results. Ideally, schedule it 10–20 days after the start of your last period.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'adolescent-gynaecology', 'contraception-counselling', 'menopause-management'],
    metaTitle: 'Cervical Cancer Screening in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Pap smear and HPV testing by Dr. Sanjana L at Health Nest and Raghava Hospital. Early detection and complete prevention in South Bangalore.',
  },
  {
    slug: 'urogynaecology',
    title: 'Urogynaecology Treatment in HSR Layout & Attibele',
    shortTitle: 'Urogynaecology',
    description: 'Treatment for urinary incontinence, pelvic organ prolapse, and bladder issues.',
    icon: 'Droplets',
    category: 'Gynaecology',
    overview: 'Urogynaecological problems such as leaking urine or pelvic pressure are very treatable. Dr. Sanjana L at Health Nest (HSR Layout) and Raghava Hospital (Attibele) offers compassionate, expert assessment and treatment, helping women regain control of their pelvic health.',
    whatToExpect: [
      'Detailed urogynaecological history and symptom assessment',
      'Pelvic examination and prolapse assessment',
      'Urodynamic testing referral if needed',
      'Pelvic floor physiotherapy referral',
      'Medical management (medications, pessaries)',
      'Surgical management (prolapse repair, incontinence procedures) when indicated',
    ],
    whenToSeeDoctor: [
      'Leaking urine when coughing, sneezing, laughing, or exercising',
      'Urgently needing the toilet and not making it in time',
      'Feeling of fullness or pressure in the vagina',
      'Visible bulge at the vaginal opening',
      'Difficulty emptying your bladder fully',
    ],
    whyChooseDrSanjana: [
      'Compassionate care for pelvic health problems at HSR and Attibele',
      'Range of conservative to surgical treatment options',
      'Integrated pelvic floor physiotherapy guidance',
      'Experience in prolapse assessment and surgical repair',
    ],
    faqs: [
      { q: 'Is urinary leakage normal after childbirth?', a: 'Urinary leakage after childbirth is common but not inevitable. With appropriate pelvic floor therapy and, if needed, medical or surgical treatment, it is very treatable. Consult Dr. Sanjana at either of our clinics.' },
    ],
    relatedSlugs: ['menopause-management', 'laparoscopic-surgery', 'postnatal-care', 'menstrual-disorders'],
    metaTitle: 'Urogynaecology Treatment in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Expert urogynaecology care for urinary incontinence and pelvic prolapse by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'adolescent-gynaecology',
    title: 'Adolescent Gynaecology in HSR Layout & Attibele',
    shortTitle: 'Adolescent Gynaecology',
    description: 'Sensitive gynaecological care for young girls and teenagers.',
    icon: 'UserRound',
    category: 'Gynaecology',
    overview: 'Adolescent gynaecology addresses the unique health needs of young girls and teenagers. Dr. Sanjana L provides a safe, confidential environment at Health Nest (HSR Layout) and Raghava Hospital (Attibele) where young women feel comfortable discussing their concerns.',
    whatToExpect: [
      'Discussion of puberty, menstrual health, and normalcy',
      'Evaluation and management of irregular or absent periods',
      'PCOS/PCOD diagnosis and management in teenagers',
      'HPV vaccination guidance',
      'Patient, age-appropriate reproductive health education',
      'Parental counselling where appropriate',
    ],
    whenToSeeDoctor: [
      'No periods by age 16 (primary amenorrhoea)',
      'Extremely painful periods limiting daily activities',
      'Irregular periods for more than 2 years after first period',
      'Unusual vaginal discharge or persistent lower abdominal pain',
      'Questions about puberty, reproductive health, or sexual health',
    ],
    whyChooseDrSanjana: [
      'Gentle, age-appropriate consultations at HSR & Attibele',
      'Confidential consultations with teenage patients',
      'Multi-lingual capability to communicate comfortably',
      'Experience diagnosing PCOS and hormonal conditions in adolescents',
    ],
    faqs: [
      { q: 'At what age should a girl have her first gynaecological appointment?', a: 'The first gynaecological visit is recommended between ages 13–15, not necessarily for an internal exam, but for education and addressing any menstrual concerns. Dr. Sanjana is available at both our locations.' },
    ],
    relatedSlugs: ['pcos-pcod-treatment', 'menstrual-disorders', 'cervical-cancer-screening', 'contraception-counselling'],
    metaTitle: 'Adolescent Gynaecology in Bangalore | HSR Layout & Attibele',
    metaDescription: 'Sensitive, compassionate gynaecological care for teenagers and young women by Dr. Sanjana L at Health Nest and Raghava Hospital, Bangalore.',
  },
  {
    slug: 'uterine-fibroids-treatment',
    title: 'Uterine Fibroids Treatment in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Uterine Fibroids',
    description: 'Accurate diagnosis and complete treatment of uterine fibroids — from medication and monitoring to fertility-sparing laparoscopic myomectomy — with Dr. Sanjana L.',
    icon: 'Activity',
    category: 'Gynaecology',
    overview: 'Uterine fibroids (myomas) are non-cancerous growths in the wall of the uterus that affect a large share of women in their 30s and 40s. Many are harmless and need only watchful monitoring, but others cause heavy or prolonged periods, pelvic pressure, frequent urination, pain during intercourse, or difficulty conceiving. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L — MBBS, MS (OBG) Gold Medalist (RGUHS), FMAS — evaluates fibroids with pelvic ultrasound and, where needed, MRI, then explains in plain language which fibroids can be left alone and which genuinely need treatment.\n\nTreatment is always matched to your age, symptoms and pregnancy plans. Options range from medical management and hormonal therapy for symptom control, to minimally invasive laparoscopic or hysteroscopic myomectomy that removes the fibroid while preserving the uterus — important for women who still wish to conceive. As a fellowship-trained laparoscopic surgeon, Dr. Sanjana favours keyhole, fertility-sparing surgery wherever it is clinically safe, so recovery is faster and scarring minimal.',
    whatToExpect: [
      'Detailed history and pelvic examination to map symptoms',
      'Pelvic ultrasound (and MRI where needed) to size and locate each fibroid',
      'Blood tests to check for anaemia from heavy bleeding',
      'A clear explanation of which fibroids need treatment and which can be monitored',
      'Medical or hormonal therapy to control bleeding where surgery is not required',
      'Fertility-sparing laparoscopic or hysteroscopic myomectomy when indicated',
      'Post-treatment follow-up and a plan for conception where relevant',
    ],
    whenToSeeDoctor: [
      'Heavy, prolonged or clotted periods that soak through protection',
      'Pelvic pressure, a feeling of fullness, or a palpable lump in the lower abdomen',
      'Frequent urination or difficulty emptying the bladder',
      'Pain during intercourse or persistent lower back pain',
      'Difficulty conceiving or recurrent pregnancy loss',
    ],
    whyChooseDrSanjana: [
      'Fellowship-trained (FMAS) in minimally invasive laparoscopic surgery',
      'Fertility-sparing myomectomy that preserves the uterus wherever possible',
      'Honest, watch-versus-treat guidance — no unnecessary surgery',
      'Care at both HSR Layout and Attibele with full theatre back-up',
    ],
    faqs: [
      { q: 'Do all uterine fibroids need surgery?', a: 'No. Many fibroids are small, symptom-free and can simply be monitored. Surgery is considered mainly when fibroids cause heavy bleeding, pain, pressure symptoms or fertility problems. Dr. Sanjana will tell you honestly whether treatment is actually needed.' },
      { q: 'Can fibroids be removed without removing the uterus?', a: 'Yes. A myomectomy removes the fibroids while keeping the uterus intact, which is important if you plan to have children. Dr. Sanjana performs laparoscopic (keyhole) and hysteroscopic myomectomy wherever it is clinically appropriate.' },
      { q: 'Do fibroids affect pregnancy and fertility?', a: 'Some fibroids, especially those that distort the uterine cavity, can make it harder to conceive or increase certain pregnancy risks. Many women with fibroids conceive and deliver normally. An assessment helps clarify your individual situation.' },
      { q: 'Where can I get fibroid treatment in HSR Layout or Attibele?', a: 'Dr. Sanjana L treats uterine fibroids at Health Nest, HSR Layout and at Raghava Multispeciality Hospital, Attibele. Call +91 94490 31003 (HSR) or +91 99800 31006 (Attibele) to book an evaluation.' },
    ],
    relatedSlugs: ['laparoscopic-surgery', 'hysterectomy', 'ovarian-cyst-treatment', 'hysteroscopy'],
    metaTitle: 'Uterine Fibroids Treatment HSR Layout & Attibele | Dr. Sanjana L',
    metaDescription: 'Fibroid treatment in HSR Layout & Attibele — diagnosis, medication and fertility-sparing laparoscopic myomectomy by Dr. Sanjana L (MS OBG, FMAS). Book an evaluation.',
  },
  {
    slug: 'ovarian-cyst-treatment',
    title: 'Ovarian Cyst Treatment in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Ovarian Cysts',
    description: 'Evaluation and treatment of ovarian cysts — from reassurance and monitoring to fertility-sparing laparoscopic cyst removal — with Dr. Sanjana L.',
    icon: 'Droplets',
    category: 'Gynaecology',
    overview: 'Ovarian cysts are fluid-filled sacs on or within the ovary, and most are functional cysts that form during the normal menstrual cycle and resolve on their own. The real task is telling a harmless cyst apart from one that needs attention — such as a cyst that is large, persistent, growing, causing pain, or showing features that warrant closer evaluation. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L uses pelvic ultrasound and, when needed, blood markers to assess a cyst accurately and calmly explain what it means for you.\n\nMost simple cysts need only reassurance and a repeat scan after a few weeks. When a cyst is large, persistent, twisted (torsion), or symptomatic, Dr. Sanjana — a fellowship-trained (FMAS) laparoscopic surgeon — can remove it through keyhole surgery that preserves healthy ovarian tissue and protects future fertility. The goal is always the least intervention that safely resolves the problem.',
    whatToExpect: [
      'Symptom review and pelvic examination',
      'Transvaginal or abdominal ultrasound to characterise the cyst',
      'Blood tests or tumour markers where the scan warrants it',
      'A clear explanation of whether the cyst is likely harmless',
      'A short interval scan to confirm functional cysts have resolved',
      'Laparoscopic ovarian cystectomy that spares healthy ovary when surgery is needed',
      'Follow-up and guidance on recurrence and hormonal health',
    ],
    whenToSeeDoctor: [
      'Sudden, severe one-sided pelvic pain (possible torsion — seek urgent care)',
      'Persistent bloating, pelvic pressure or a dull ache',
      'Pain during intercourse or during periods',
      'Irregular periods alongside pelvic discomfort',
      'A cyst found on a scan that your doctor wants reviewed',
    ],
    whyChooseDrSanjana: [
      'Calm, accurate assessment that avoids over-treatment of simple cysts',
      'Fellowship-trained (FMAS) keyhole ovarian cystectomy',
      'Ovary- and fertility-preserving surgical approach',
      'Care at both HSR Layout and Attibele with theatre and anaesthesia back-up',
    ],
    faqs: [
      { q: 'Are ovarian cysts dangerous?', a: 'Most ovarian cysts are functional and harmless, and they resolve on their own within a few menstrual cycles. A minority need treatment because they are large, persistent, painful or have concerning features on a scan. An ultrasound helps decide which category yours falls into.' },
      { q: 'Will I need surgery for an ovarian cyst?', a: 'Often not. Simple cysts are usually just monitored with a repeat scan. Surgery is considered for cysts that are large, growing, twisted or symptomatic. When surgery is needed, laparoscopic (keyhole) removal that preserves the ovary is usually possible.' },
      { q: 'Can an ovarian cyst affect my fertility?', a: 'Most cysts do not affect fertility. Some conditions linked to cysts, such as endometriomas or PCOS, can, which is why proper evaluation matters. Dr. Sanjana takes your fertility plans into account before recommending any treatment.' },
      { q: 'Where can I get ovarian cyst treatment near HSR Layout or Attibele?', a: 'Dr. Sanjana L evaluates and treats ovarian cysts at Health Nest, HSR Layout and Raghava Multispeciality Hospital, Attibele. Call +91 94490 31003 (HSR) or +91 99800 31006 (Attibele) to book.' },
    ],
    relatedSlugs: ['laparoscopic-surgery', 'uterine-fibroids-treatment', 'pcos-pcod-treatment', 'endometriosis-treatment'],
    metaTitle: 'Ovarian Cyst Treatment HSR Layout & Attibele | Dr. Sanjana L',
    metaDescription: 'Ovarian cyst treatment in HSR Layout & Attibele — accurate ultrasound assessment and fertility-sparing laparoscopic cyst removal by Dr. Sanjana L (MS OBG, FMAS).',
  },
  {
    slug: 'endometriosis-treatment',
    title: 'Endometriosis Treatment in HSR Layout & Attibele, Bangalore',
    shortTitle: 'Endometriosis',
    description: 'Diagnosis and long-term care for endometriosis — pain relief, hormonal therapy and laparoscopic excision — with Dr. Sanjana L.',
    icon: 'HeartPulse',
    category: 'Gynaecology',
    overview: 'Endometriosis is a condition where tissue similar to the uterine lining grows outside the uterus, causing painful periods, chronic pelvic pain, pain during intercourse and, for some women, difficulty conceiving. It is often under-diagnosed for years because the pain is dismissed as normal. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L takes these symptoms seriously, combining a careful history, examination and ultrasound to reach a diagnosis and start relief sooner rather than later.\n\nCare is individualised and long-term. Depending on your symptoms, severity and whether you are trying to conceive, treatment may include pain management, hormonal therapy to slow the disease, and — for confirmed or advanced disease — laparoscopic excision of endometriotic tissue. As a fellowship-trained (FMAS) laparoscopic surgeon, Dr. Sanjana can both confirm the diagnosis and treat it in the same keyhole procedure where appropriate, with a clear plan to protect fertility and quality of life.',
    whatToExpect: [
      'A history that takes your pain and its impact seriously',
      'Pelvic examination and ultrasound to look for endometriomas and signs of disease',
      'A staged treatment plan based on symptoms and fertility goals',
      'Pain-management and hormonal options to control symptoms',
      'Laparoscopy to confirm and excise endometriosis when indicated',
      'Fertility assessment and referral or co-management if conception is delayed',
      'Long-term follow-up to manage recurrence',
    ],
    whenToSeeDoctor: [
      'Painful periods that disrupt work, study or daily life',
      'Chronic pelvic pain between periods',
      'Pain during or after intercourse',
      'Painful bowel movements or urination during periods',
      'Difficulty conceiving alongside painful periods',
    ],
    whyChooseDrSanjana: [
      'Symptoms taken seriously — faster diagnosis, less delay',
      'Fellowship-trained (FMAS) in laparoscopic excision of endometriosis',
      'Fertility-aware planning for women trying to conceive',
      'Continuity of care at both HSR Layout and Attibele',
    ],
    faqs: [
      { q: 'How is endometriosis diagnosed?', a: 'Diagnosis starts with your symptom history, a pelvic examination and an ultrasound, which can detect endometriomas and some signs of disease. Laparoscopy remains the most definitive way to confirm and stage endometriosis, and it allows treatment during the same procedure.' },
      { q: 'Can endometriosis be cured?', a: 'There is no permanent cure, but endometriosis can be managed very effectively. Pain relief, hormonal therapy and laparoscopic excision can control symptoms, improve quality of life and support fertility. Long-term follow-up helps manage any recurrence.' },
      { q: 'Does endometriosis cause infertility?', a: 'Endometriosis can make conceiving harder for some women, but many conceive naturally or with support. If you are trying to conceive, Dr. Sanjana factors that into the treatment plan and coordinates fertility care where needed.' },
      { q: 'Where can I get endometriosis treatment near HSR Layout or Attibele?', a: 'Dr. Sanjana L diagnoses and treats endometriosis at Health Nest, HSR Layout and Raghava Multispeciality Hospital, Attibele. Call +91 94490 31003 (HSR) or +91 99800 31006 (Attibele) to book a consultation.' },
    ],
    relatedSlugs: ['laparoscopic-surgery', 'menstrual-disorders', 'fertility-treatment', 'ovarian-cyst-treatment'],
    metaTitle: 'Endometriosis Treatment HSR Layout & Attibele | Dr. Sanjana L',
    metaDescription: 'Endometriosis treatment in HSR Layout & Attibele — timely diagnosis, pain and hormonal therapy, and laparoscopic excision by Dr. Sanjana L (MS OBG, FMAS).',
  },
  {
    slug: 'white-discharge-leucorrhoea',
    title: 'White Discharge (Leucorrhoea) Treatment in HSR Layout & Attibele',
    shortTitle: 'White Discharge (Leucorrhoea)',
    description: 'Evaluation and treatment of white discharge and leucorrhoea — finding the cause and treating it — with Dr. Sanjana L.',
    icon: 'Droplets',
    category: 'Gynaecology',
    overview: 'Some vaginal discharge is completely normal and changes through the menstrual cycle. It becomes a concern when it turns heavy, discoloured, foul-smelling, or comes with itching, burning or discomfort — often a sign of an infection or a hormonal imbalance rather than something to be embarrassed about. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L evaluates white discharge (leucorrhoea) calmly and confidentially to find the actual cause instead of guessing.\n\nTreatment depends on the cause. A simple examination and, where needed, a swab or test can identify bacterial, fungal (candida) or other infections, which respond well to the right targeted medication. Recurrent or hormone-related discharge is managed with a clear plan and follow-up. The aim is lasting relief and reassurance, with sensitive care throughout.',
    whatToExpect: [
      'A private, non-judgemental discussion of your symptoms',
      'Examination and, where needed, a simple swab or test to find the cause',
      'Identification of infection (bacterial, fungal) versus hormonal causes',
      'Targeted medication for the specific cause rather than guesswork',
      'Guidance on intimate hygiene and preventing recurrence',
      'A follow-up plan for recurrent or persistent discharge',
      'Screening advice where discharge needs further evaluation',
    ],
    whenToSeeDoctor: [
      'Discharge that is heavy, thick, green, grey or foul-smelling',
      'Itching, burning, redness or swelling around the vagina',
      'Discomfort or pain during urination or intercourse',
      'Discharge with spotting between periods',
      'Recurrent discharge that keeps coming back after treatment',
    ],
    whyChooseDrSanjana: [
      'Confidential, sensitive and non-judgemental care',
      'Cause-first approach — the right test before the right medicine',
      'Clear guidance on preventing recurrence',
      'Care at both HSR Layout and Attibele',
    ],
    faqs: [
      { q: 'Is white discharge normal?', a: 'A certain amount of clear or milky discharge is normal and varies through the menstrual cycle. It needs attention when it becomes heavy, discoloured or foul-smelling, or comes with itching, burning or pain — these can signal an infection or hormonal imbalance worth checking.' },
      { q: 'What causes leucorrhoea?', a: 'Common causes include bacterial or fungal (yeast) infections, hormonal changes, and sometimes poor intimate hygiene or irritation. A simple examination and, where needed, a swab helps identify the exact cause so treatment can be targeted.' },
      { q: 'How is white discharge treated?', a: 'Treatment depends on the cause — antifungal or antibacterial medication for infections, and a hormonal or lifestyle plan where relevant. Dr. Sanjana treats the specific cause rather than prescribing blindly, which gives faster, longer-lasting relief.' },
      { q: 'Where can I get treatment for white discharge near HSR Layout or Attibele?', a: 'Dr. Sanjana L offers confidential evaluation and treatment at Health Nest, HSR Layout and Raghava Multispeciality Hospital, Attibele. Call +91 94490 31003 (HSR) or +91 99800 31006 (Attibele) to book.' },
    ],
    relatedSlugs: ['uti-vaginal-infections', 'menstrual-disorders', 'cervical-cancer-screening', 'contraception-counselling'],
    metaTitle: 'White Discharge (Leucorrhoea) Treatment HSR Layout & Attibele',
    metaDescription: 'Confidential white discharge & leucorrhoea treatment in HSR Layout & Attibele — cause-first evaluation and targeted care by Dr. Sanjana L (MS OBG). Book a visit.',
  },
  {
    slug: 'uti-vaginal-infections',
    title: 'UTI & Vaginal Infection Treatment for Women in HSR Layout & Attibele',
    shortTitle: 'UTI & Vaginal Infections',
    description: 'Fast, confidential treatment of urinary tract infections and vaginal infections in women — including recurrent cases — with Dr. Sanjana L.',
    icon: 'Shield',
    category: 'Gynaecology',
    overview: 'Urinary tract infections (UTIs) and vaginal infections are among the most common reasons women see a gynaecologist — and among the most uncomfortable. Burning during urination, frequent urges, lower abdominal discomfort, itching or unusual discharge are all signals worth acting on early, before a simple infection becomes a recurring problem. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L provides prompt, confidential diagnosis and treatment so you feel better quickly.\n\nFor one-off infections, the right test and a targeted course of medication usually resolve things fast. For recurrent UTIs or infections that keep returning, Dr. Sanjana looks deeper — at underlying causes, hygiene, hormonal factors and, in some cases, further evaluation — and builds a prevention plan so you are not caught in a cycle of repeat infections.',
    whatToExpect: [
      'Prompt review of your symptoms, often same-day where possible',
      'Urine test or vaginal swab to confirm the type of infection',
      'A targeted course of medication for the specific infection',
      'Assessment of causes if infections keep recurring',
      'A practical prevention plan (hydration, hygiene, hormonal factors)',
      'Further evaluation for complicated or recurrent cases',
      'Follow-up to confirm the infection has fully cleared',
    ],
    whenToSeeDoctor: [
      'Burning or pain when passing urine',
      'Frequent or urgent need to urinate, or blood in urine',
      'Lower abdominal or pelvic discomfort with urinary symptoms',
      'Vaginal itching, burning or unusual discharge',
      'Infections that keep coming back after treatment',
    ],
    whyChooseDrSanjana: [
      'Prompt, confidential care to relieve symptoms quickly',
      'Targeted treatment based on the actual infection, not guesswork',
      'A real prevention plan for recurrent infections',
      'Care at both HSR Layout and Attibele',
    ],
    faqs: [
      { q: 'What are the signs of a UTI in women?', a: 'Common signs are burning during urination, a frequent or urgent need to urinate, cloudy or strong-smelling urine, and lower abdominal discomfort. If there is fever, back pain or blood in the urine, see a doctor promptly as the infection may be spreading.' },
      { q: 'Why do I keep getting UTIs or vaginal infections?', a: 'Recurrent infections can be linked to hygiene, hormonal changes (including around menopause), incomplete previous treatment, or other underlying factors. Dr. Sanjana looks for the cause and builds a prevention plan rather than just treating each episode.' },
      { q: 'Are these infections treated confidentially?', a: 'Yes. Consultations are private and non-judgemental. Dr. Sanjana diagnoses the specific infection with a simple test and prescribes targeted treatment, along with advice to prevent it recurring.' },
      { q: 'Where can I get UTI or infection treatment near HSR Layout or Attibele?', a: 'Dr. Sanjana L treats UTIs and vaginal infections at Health Nest, HSR Layout and Raghava Multispeciality Hospital, Attibele. Call +91 94490 31003 (HSR) or +91 99800 31006 (Attibele) to book.' },
    ],
    relatedSlugs: ['white-discharge-leucorrhoea', 'urogynaecology', 'menstrual-disorders', 'cervical-cancer-screening'],
    metaTitle: 'UTI & Vaginal Infection Treatment for Women | HSR Layout & Attibele',
    metaDescription: 'Fast, confidential UTI and vaginal infection treatment for women in HSR Layout & Attibele, including recurrent cases, by Dr. Sanjana L (MS OBG). Book a visit.',
  },
  {
    slug: 'heavy-irregular-periods',
    title: 'Heavy & Irregular Periods (Menorrhagia) Treatment in HSR Layout & Attibele',
    shortTitle: 'Heavy & Irregular Periods',
    description: 'Diagnosis and treatment for heavy bleeding and irregular periods — finding the cause and restoring control — with Dr. Sanjana L.',
    icon: 'Activity',
    category: 'Gynaecology',
    overview: 'Periods that are very heavy, prolonged, or unpredictable are not something you simply have to live with — and they are often a sign of a treatable underlying cause. Soaking through protection every hour, passing large clots, periods lasting more than seven days, or cycles that are wildly irregular can point to hormonal imbalance, fibroids, polyps, thyroid issues, PCOS or other conditions. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L investigates heavy and irregular periods properly rather than dismissing them.\n\nAfter identifying the cause with blood tests, an ultrasound and, where needed, hysteroscopy, treatment is matched to you — from medical and hormonal management to minimally invasive procedures for fibroids or polyps. As a fellowship-trained (FMAS) laparoscopic surgeon, Dr. Sanjana can offer keyhole options where surgery is the right answer, always with your fertility plans in mind. This page focuses on heavy and irregular bleeding; for the full range of period problems see our menstrual disorders page.',
    whatToExpect: [
      'A detailed cycle and symptom history, including how bleeding affects daily life',
      'Blood tests for anaemia, thyroid and hormonal causes',
      'Pelvic ultrasound to check for fibroids, polyps or PCOS',
      'Hysteroscopy where the uterine cavity needs closer assessment',
      'Medical or hormonal treatment to control bleeding',
      'Minimally invasive procedures for fibroids or polyps when indicated',
      'Follow-up to confirm bleeding and any anaemia have improved',
    ],
    whenToSeeDoctor: [
      'Soaking through a pad or tampon every hour for several hours',
      'Periods lasting longer than seven days or passing large clots',
      'Bleeding between periods or after intercourse',
      'Very irregular or unpredictable cycles',
      'Tiredness, breathlessness or dizziness from heavy bleeding (anaemia)',
    ],
    whyChooseDrSanjana: [
      'Heavy bleeding investigated properly, not dismissed',
      'Cause-first diagnosis with tests, ultrasound and hysteroscopy',
      'Fellowship-trained (FMAS) for keyhole options when needed',
      'Fertility-aware treatment planning at HSR Layout and Attibele',
    ],
    faqs: [
      { q: 'When are heavy periods a problem worth treating?', a: 'Heavy periods (menorrhagia) are worth checking when you soak through protection hourly, pass large clots, bleed for more than seven days, or feel tired and breathless from blood loss. These can point to fibroids, polyps, hormonal or thyroid issues — most of which are treatable.' },
      { q: 'What causes irregular periods?', a: 'Common causes include PCOS, thyroid problems, hormonal imbalance, stress, fibroids or polyps, and perimenopause. Dr. Sanjana uses blood tests and an ultrasound to find the specific cause before recommending treatment.' },
      { q: 'Do I need surgery for heavy periods?', a: 'Often not. Many cases respond to medical or hormonal treatment. Surgery — usually minimally invasive — is considered when fibroids or polyps are the cause, or when other treatments have not worked. Your fertility plans are always part of the decision.' },
      { q: 'Where can I get treatment for heavy or irregular periods near HSR Layout or Attibele?', a: 'Dr. Sanjana L treats heavy and irregular periods at Health Nest, HSR Layout and Raghava Multispeciality Hospital, Attibele. Call +91 94490 31003 (HSR) or +91 99800 31006 (Attibele) to book.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'pcos-pcod-treatment', 'uterine-fibroids-treatment', 'hysterectomy'],
    metaTitle: 'Heavy & Irregular Periods (Menorrhagia) Treatment | HSR Layout & Attibele',
    metaDescription: 'Treatment for heavy bleeding and irregular periods in HSR Layout & Attibele — cause-first diagnosis and fertility-aware care by Dr. Sanjana L (MS OBG, FMAS).',
  },
  {
    slug: 'hysterectomy',
    title: 'Hysterectomy (Uterus Removal) in HSR Layout & Attibele',
    shortTitle: 'Hysterectomy',
    description: 'Laparoscopic, vaginal and abdominal hysterectomy — with a frank assessment of whether you need one at all.',
    icon: 'Scissors',
    category: 'Surgery',
    overview: 'Hysterectomy is one of the most commonly recommended operations in Indian gynaecology, and one of the most commonly recommended too early. Before agreeing to have your uterus removed you are entitled to two things: a clear statement of which specific problem the operation is solving, and an honest account of what could be done instead. At Health Nest (HSR Layout) and Raghava Multispeciality Hospital (Attibele), Dr. Sanjana L — MBBS, MS (OBG) Gold Medalist (RGUHS), FMAS — treats that conversation as the important part of the decision, not the paperwork before it.\n\nThere are conditions where hysterectomy is genuinely the right answer: fibroids causing severe bleeding and anaemia in a woman who has completed her family, adenomyosis that has not responded to medical treatment, uterine prolapse, persistent abnormal bleeding that has failed other management, and certain pre-cancerous or cancerous conditions. There are also many situations where it is offered too readily — fibroids that could be removed on their own by myomectomy, heavy bleeding that responds to a hormonal intrauterine device or medical treatment, and pain that has not yet been properly investigated. Which of these applies to you should be stated explicitly.\n\nWhere surgery is the right decision, the route matters. Laparoscopic and vaginal hysterectomy avoid a large abdominal incision and typically mean a shorter hospital stay and a faster return to normal life than open surgery. Whether the ovaries are removed is a separate decision from removing the uterus, and for most women below the age of menopause the ovaries can and often should be conserved — removing them triggers immediate surgical menopause, which has long-term consequences that deserve to be discussed rather than bundled into the same consent form.',
    whatToExpect: [
      'A clear statement of which problem the hysterectomy is meant to solve',
      'The alternatives set out honestly — myomectomy, hormonal IUD, medical management, ablation',
      'Ultrasound, hysteroscopy or biopsy as needed to confirm the diagnosis first',
      'A separate, explicit discussion about whether the ovaries are removed or conserved',
      'Choice of route explained — laparoscopic, vaginal or abdominal, and why',
      'Pre-operative bloods, anaesthetic assessment and a written consent conversation',
      'Structured recovery plan, including when you can lift, drive and return to work',
      'Follow-up at six weeks and guidance on what changes afterwards and what does not',
    ],
    whenToSeeDoctor: [
      'You have been advised a hysterectomy and want a second opinion before agreeing',
      'Heavy bleeding with anaemia that has not settled with medical treatment',
      'Fibroids or adenomyosis causing pain, pressure or bleeding that affects daily life',
      'A sensation of something coming down, or urinary leakage, suggesting prolapse',
      'Bleeding after menopause, or abnormal bleeding that has not been investigated',
      'Persistent pelvic pain that has not been given a proper diagnosis',
    ],
    whyChooseDrSanjana: [
      'A frank assessment of whether the operation is needed at all',
      'Uterus-preserving alternatives offered first wherever they are reasonable',
      'FMAS fellowship-trained in minimal access surgery — keyhole and vaginal routes where suitable',
      'Ovarian conservation discussed as its own decision, not bundled in',
      'Surgery and follow-up at Health Nest (HSR Layout) and Raghava Hospital (Attibele)',
    ],
    faqs: [
      { q: 'Do I really need a hysterectomy?', a: 'Often not. Many women advised a hysterectomy for fibroids or heavy bleeding have effective alternatives — myomectomy to remove fibroids and keep the uterus, a hormonal intrauterine device, medical management, or endometrial ablation. Hysterectomy is clearly indicated for some conditions, but you should be told which specific finding is driving the recommendation and what happens if you wait. A second opinion before consenting is entirely reasonable.' },
      { q: 'What are the types of hysterectomy?', a: 'By extent: total (uterus and cervix), subtotal (uterus only, cervix left), and radical (for cancer). By route: abdominal through an incision, vaginal through the vagina with no external cut, and laparoscopic through keyhole incisions. Route depends on the size of the uterus, the reason for surgery, previous operations and whether prolapse is present.' },
      { q: 'Will my ovaries be removed too?', a: 'Not necessarily, and it is a separate decision. For most women who have not reached menopause, conserving the ovaries is preferred — removing them causes immediate surgical menopause with hot flushes and long-term effects on bone and cardiovascular health. Removal is considered for specific reasons such as ovarian disease or a high genetic risk. Ask for this to be discussed on its own terms.' },
      { q: 'How long does recovery take?', a: 'After laparoscopic or vaginal hysterectomy, most women go home in one to three days and return to light activity within two to three weeks, with full recovery around six weeks. Open abdominal surgery typically takes six to eight weeks. Heavy lifting is restricted for around six weeks in all cases to protect the internal healing.' },
      { q: 'Will I go into menopause after a hysterectomy?', a: 'Not if your ovaries are conserved. Your periods stop because the uterus is gone, but the ovaries continue producing hormones and you go through menopause at roughly your natural age — sometimes slightly earlier. If both ovaries are removed, menopause begins immediately and hormone therapy is usually discussed.' },
      { q: 'Where is hysterectomy performed by Dr. Sanjana?', a: 'At Health Nest, 1162, 24th Main Rd, Sector 2, HSR Layout (+91 94490 31003) and Raghava Multispeciality Hospital, Sarjapura–Attibele Road, Attibele (+91 99800 31006). Route and location are decided from your case. Book a consultation to have the decision assessed properly first.' },
    ],
    relatedSlugs: ['laparoscopic-surgery', 'uterine-fibroids-treatment', 'heavy-irregular-periods', 'urogynaecology'],
    metaTitle: 'Hysterectomy (Uterus Removal) | HSR Layout & Attibele',
    metaDescription: 'Hysterectomy in HSR Layout & Attibele by Dr. Sanjana L (MS OBG, FMAS) — laparoscopic, vaginal and abdominal, with an honest review of whether you need one.',
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(s => s.slug === slug);
}

export function getRelatedServices(slugs: string[]): Service[] {
  return slugs.map(s => services.find(svc => svc.slug === s)).filter(Boolean) as Service[];
}

export const serviceCategories = ['Obstetrics', 'Fertility', 'Surgery', 'Gynaecology'];
