// lib/services.ts
export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  category: string;
  overview: string;
  whatToExpect: string[];
  whenToSeeDoctor: string[];
  whyChooseDrSanjana: string[];
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
  metaTitle: string;
  metaDescription: string;
}

export const services: Service[] = [
  {
    slug: 'pregnancy-care',
    title: 'Pregnancy Care in HSR Layout, Bangalore',
    shortTitle: 'Pregnancy Care',
    description: 'Comprehensive prenatal support from conception to delivery.',
    icon: 'Baby',
    category: 'Obstetrics',
    overview: 'Pregnancy is one of the most beautiful journeys of your life, and you deserve expert, compassionate care every step of the way. At Health Nest, Dr. Sanjana L provides comprehensive pregnancy care tailored to your unique needs — from your first prenatal visit through safe delivery and beyond. With 15+ years of experience managing both routine and complex pregnancies, Dr. Sanjana ensures you feel informed, supported, and confident throughout your journey to motherhood.',
    whatToExpect: [
      'Initial consultation and dating scan in the first trimester',
      'Regular prenatal check-ups every 4 weeks (adjusting closer to delivery)',
      'Blood tests, anomaly scans, and glucose tolerance screening',
      'Nutrition guidance, weight monitoring, and exercise advice',
      'Birth planning discussion and delivery preparation',
      'Postpartum follow-up and breastfeeding support',
    ],
    whenToSeeDoctor: [
      'As soon as you suspect you are pregnant',
      'If you experience heavy bleeding, severe cramps, or unusual discharge',
      'Reduced fetal movements after 28 weeks',
      'Severe headache, blurred vision, or swollen hands/feet',
      'Any concerns about your baby\'s growth or wellbeing',
    ],
    whyChooseDrSanjana: [
      '15+ years managing both routine and high-risk pregnancies',
      'Multilingual consultations (English, Hindi, Kannada, Telugu)',
      'Personalised birth plans and patient-centred approach',
      'Seamless coordination with the delivery team for your comfort',
    ],
    faqs: [
      { q: 'When should I book my first prenatal appointment?', a: 'Ideally book your first appointment as soon as you get a positive pregnancy test, typically between 6–8 weeks of pregnancy. Early visits help confirm healthy fetal development and establish your care plan.' },
      { q: 'How many prenatal visits are recommended?', a: 'A standard pregnancy involves about 10–12 prenatal visits. These are more frequent early on and as your due date approaches. High-risk pregnancies may require additional monitoring.' },
      { q: 'Does Dr. Sanjana deliver babies?', a: 'Yes, Dr. Sanjana L manages deliveries and will guide you through your birth plan, whether you are aiming for a normal vaginal delivery or a planned caesarean section.' },
    ],
    relatedSlugs: ['high-risk-pregnancy', 'normal-delivery', 'prenatal-screening', 'postnatal-care'],
    metaTitle: 'Pregnancy Care in HSR Layout Bangalore | Dr. Sanjana L - Health Nest',
    metaDescription: 'Comprehensive pregnancy care at Health Nest, HSR Layout. Dr. Sanjana L provides prenatal check-ups, ultrasound guidance, high-risk pregnancy management & safe deliveries.',
  },
  {
    slug: 'high-risk-pregnancy',
    title: 'High Risk Pregnancy Management in Bangalore',
    shortTitle: 'High-Risk Pregnancy',
    description: 'Expert management for gestational diabetes, preeclampsia, and complex pregnancies.',
    icon: 'HeartPulse',
    category: 'Obstetrics',
    overview: 'A high-risk pregnancy requires a higher level of monitoring, expertise, and compassionate care. Dr. Sanjana L at Health Nest specialises in managing conditions such as gestational diabetes, preeclampsia, multiple pregnancies, advanced maternal age, and prior pregnancy complications. With state-of-the-art diagnostic tools and a patient-centred philosophy, Dr. Sanjana ensures that both you and your baby receive the vigilant attention necessary for the best possible outcome.',
    whatToExpect: [
      'Detailed risk assessment and personalised monitoring plan',
      'Frequent ultrasounds and fetal well-being tests',
      'Specialist coordination for conditions like diabetes or cardiac issues',
      'Growth scans (every 2–4 weeks) to monitor fetal development',
      'Daily kick count guidance and warning sign education',
      'Planned delivery timing and mode based on your specific condition',
    ],
    whenToSeeDoctor: [
      'Diagnosis of gestational diabetes or pre-existing diabetes',
      'History of preeclampsia, preterm birth, or pregnancy loss',
      'Carrying twins, triplets, or higher-order multiples',
      'Advanced maternal age (35+ years)',
      'Chronic conditions like hypertension, thyroid disorders, or autoimmune diseases',
    ],
    whyChooseDrSanjana: [
      'Extensive experience in managing complex, high-risk pregnancies',
      'Close coordination with endocrinologists, cardiologists, and neonatologists',
      'Evidence-based protocols for best maternal and fetal outcomes',
      'Compassionate, anxiety-reducing communication throughout your pregnancy',
    ],
    faqs: [
      { q: 'What qualifies a pregnancy as high-risk?', a: 'A pregnancy is considered high-risk when there are conditions that could affect the health of the mother, baby, or both. Common reasons include gestational diabetes, hypertension, multiple pregnancies, advanced maternal age, and previous complicated deliveries.' },
      { q: 'Can a high-risk pregnancy result in a normal delivery?', a: 'Yes, many women with high-risk pregnancies go on to have safe vaginal deliveries. The mode of delivery depends on your specific case and will be decided collaboratively with Dr. Sanjana as your due date approaches.' },
    ],
    relatedSlugs: ['pregnancy-care', 'normal-delivery', 'cesarean-delivery', 'prenatal-screening'],
    metaTitle: 'High Risk Pregnancy Specialist in Bangalore | Health Nest HSR Layout',
    metaDescription: 'Expert high-risk pregnancy management by Dr. Sanjana L at Health Nest. Experienced in gestational diabetes, preeclampsia, multiple pregnancies & more.',
  },
  {
    slug: 'normal-delivery',
    title: 'Normal Delivery in HSR Layout Bangalore',
    shortTitle: 'Normal Delivery',
    description: 'Safe, supportive vaginal delivery care with experienced guidance.',
    icon: 'Smile',
    category: 'Obstetrics',
    overview: 'A natural, vaginal delivery is often the most beneficial outcome for both mother and baby. Dr. Sanjana L at Health Nest supports and encourages normal deliveries for eligible women, providing expert guidance, labour support, and evidence-based pain management options. She believes in empowering mothers with knowledge and choice while ensuring the highest safety standards for you and your newborn.',
    whatToExpect: [
      'Birth planning consultation discussing your preferences',
      'Labour monitoring with cardiotocography (CTG)',
      'Access to pain relief options including epidural guidance',
      'Active pushing support by Dr. Sanjana and her team',
      'Immediate skin-to-skin contact and breastfeeding initiation',
      'Postnatal monitoring and recovery support',
    ],
    whenToSeeDoctor: [
      'Regular uterine contractions that are increasing in frequency',
      'Water breaking (rupture of membranes)',
      'Decrease in fetal movements near term',
      'Any bleeding or unusual discharge during late pregnancy',
    ],
    whyChooseDrSanjana: [
      'Strong track record of supporting successful normal deliveries',
      'Patient-led birth planning with informed decision-making',
      'Available and accessible during active labour',
      'Experienced in managing shoulder dystocia and other labour complications',
    ],
    faqs: [
      { q: 'Is normal delivery better than caesarean?', a: 'Generally, vaginal delivery offers faster recovery, lower risk of surgical complications, and benefits for the baby such as exposure to beneficial bacteria. However, the best option depends on your individual circumstances. Dr. Sanjana will guide you based on your health and your baby\'s position.' },
      { q: 'What pain relief options are available during labour?', a: 'Options include breathing techniques, positions, warm compresses, and epidural anaesthesia. Dr. Sanjana will discuss all options with you during your birth planning session.' },
    ],
    relatedSlugs: ['pregnancy-care', 'cesarean-delivery', 'postnatal-care', 'high-risk-pregnancy'],
    metaTitle: 'Normal Delivery Doctor in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Safe and supportive normal delivery care at Health Nest, HSR Layout. Dr. Sanjana L guides you through vaginal birth with expert care and compassion.',
  },
  {
    slug: 'cesarean-delivery',
    title: 'Caesarean Delivery (C-Section) in Bangalore',
    shortTitle: 'Caesarean Delivery',
    description: 'Safe, skilled caesarean sections when medically indicated or planned.',
    icon: 'Stethoscope',
    category: 'Obstetrics',
    overview: 'When a normal vaginal delivery is not possible or poses risks to mother or baby, a caesarean section (C-section) is a life-saving surgical intervention performed by Dr. Sanjana L with exceptional skill and care. Whether planned in advance or performed as an emergency, Dr. Sanjana ensures the procedure is carried out safely, with clear communication, minimal discomfort, and a focus on quick recovery.',
    whatToExpect: [
      'Pre-operative consultation explaining the procedure fully',
      'Anaesthesia discussion (spinal or general)',
      'Surgical incision and delivery — typically within 10 minutes',
      'Immediate newborn assessment and early breastfeeding support',
      'Post-operative pain management and wound care',
      'Recovery guidance and follow-up appointments',
    ],
    whenToSeeDoctor: [
      'Previous caesarean delivery (VBAC may be possible — discuss options)',
      'Breech or transverse baby position near term',
      'Placenta previa or accreta',
      'Twin pregnancies with complex positions',
      'Foetal distress during labour',
    ],
    whyChooseDrSanjana: [
      'Extensive surgical experience in both elective and emergency C-sections',
      'Gentle surgical technique minimising recovery time',
      'Clear pre-operative counselling and post-op support',
      'Experience with VBAC counselling for women with prior C-sections',
    ],
    faqs: [
      { q: 'Is recovery from C-section painful?', a: 'Discomfort is expected but well-managed with appropriate pain relief. Most women are up and walking within 24 hours. Full recovery typically takes 4–6 weeks, and Dr. Sanjana provides detailed aftercare instructions.' },
      { q: 'Can I have a normal delivery after a C-section?', a: 'Yes, in many cases a Vaginal Birth After Caesarean (VBAC) is possible. Dr. Sanjana will assess your specific situation and discuss the risks and benefits with you.' },
    ],
    relatedSlugs: ['normal-delivery', 'pregnancy-care', 'high-risk-pregnancy', 'postnatal-care'],
    metaTitle: 'Caesarean Delivery (C-Section) in Bangalore | Health Nest HSR Layout',
    metaDescription: 'Safe and skilled caesarean section surgery by Dr. Sanjana L at Health Nest, HSR Layout. Expert planned and emergency C-section care in Bangalore.',
  },
  {
    slug: 'fertility-treatment',
    title: 'Fertility Treatment in HSR Layout Bangalore',
    shortTitle: 'Fertility Treatment',
    description: 'Comprehensive fertility evaluation and treatment to help you conceive.',
    icon: 'Flower2',
    category: 'Fertility',
    overview: 'Struggling to conceive can be an emotionally challenging experience. At Health Nest, Dr. Sanjana L offers compassionate, evidence-based fertility evaluation and treatment, helping couples understand the root cause of their difficulty and offering a clear path forward. From basic investigations to advanced treatments like IUI and IVF referral, every step is taken with sensitivity and personalised care.',
    whatToExpect: [
      'Detailed fertility consultation for both partners',
      'Hormonal blood tests (FSH, LH, AMH, thyroid)',
      'Semen analysis and male factor evaluation',
      'Pelvic ultrasound to assess ovarian reserve and uterine health',
      'Ovulation tracking and induction cycles if needed',
      'IUI (Intrauterine Insemination) support',
      'IVF referral and co-management with fertility specialists',
    ],
    whenToSeeDoctor: [
      'Trying to conceive for 12+ months (under 35) or 6+ months (over 35)',
      'Irregular or absent periods',
      'Prior diagnosis of PCOS, endometriosis, or fibroids',
      'History of recurrent miscarriages',
      'Male partner with known fertility issues',
    ],
    whyChooseDrSanjana: [
      'Empathetic, non-judgmental approach to fertility challenges',
      'Comprehensive investigations to identify root causes',
      'Experience with ovulation induction and IUI procedures',
      'Trusted referral network for IVF and ART specialists',
    ],
    faqs: [
      { q: 'When should a couple seek fertility help?', a: 'If you are under 35 and have been trying to conceive for 12 months without success, or over 35 and trying for 6 months, it is a good time to seek evaluation. Women with known conditions like PCOS or endometriosis can seek help earlier.' },
      { q: 'What is IUI?', a: 'Intrauterine Insemination (IUI) is a fertility procedure where processed sperm is placed directly into the uterus around ovulation. It is less invasive than IVF and is often a first-line treatment for certain types of infertility.' },
    ],
    relatedSlugs: ['ivf-iui', 'pcos-pcod-treatment', 'menstrual-disorders', 'pregnancy-care'],
    metaTitle: 'Fertility Treatment in HSR Layout Bangalore | IVF, IUI - Health Nest',
    metaDescription: 'Struggling to conceive? Dr. Sanjana L offers fertility evaluation, IUI, IVF counselling & treatment at Health Nest, HSR Layout.',
  },
  {
    slug: 'ivf-iui',
    title: 'IVF & IUI Treatment in Bangalore | Health Nest',
    shortTitle: 'IVF & IUI',
    description: 'Advanced assisted reproductive technology for couples facing infertility.',
    icon: 'Microscope',
    category: 'Fertility',
    overview: 'When natural conception and simpler fertility treatments have not been successful, assisted reproductive technologies (ART) like IUI and IVF can significantly improve your chances of conception. Dr. Sanjana L at Health Nest guides couples through these procedures with expert medical management, emotional support, and trusted referrals to specialised ART centres when required.',
    whatToExpect: [
      'Thorough pre-ART evaluation and counselling',
      'IUI: Ovarian stimulation, monitoring scans, and insemination',
      'IVF: Co-management with your IVF centre — egg retrieval, fertilisation, embryo transfer',
      'Luteal phase support and early pregnancy monitoring',
      'Hormonal support and follow-up throughout treatment cycles',
    ],
    whenToSeeDoctor: [
      'Failed IUI cycles (typically 3–4 attempts)',
      'Severely compromised sperm parameters',
      'Tubal factor infertility',
      'Advanced maternal age with diminished ovarian reserve',
      'Recurrent implantation failure',
    ],
    whyChooseDrSanjana: [
      'Experience in IUI procedures with high success orientation',
      'Coordination with top IVF labs in Bangalore',
      'Supportive counselling throughout emotionally demanding cycles',
      'Clear explanation of costs, timelines, and realistic expectations',
    ],
    faqs: [
      { q: 'What is the success rate of IVF?', a: 'IVF success rates vary based on age, diagnosis, and clinic. Generally, rates are 40–50% per cycle for women under 35, declining with age. Dr. Sanjana will give you a realistic expectation based on your individual profile.' },
      { q: 'How many IUI cycles should I try before moving to IVF?', a: 'Typically 3–4 IUI cycles are recommended before considering IVF, though this depends on your age, diagnosis, and how you are responding to treatment.' },
    ],
    relatedSlugs: ['fertility-treatment', 'pcos-pcod-treatment', 'menstrual-disorders', 'pregnancy-care'],
    metaTitle: 'IVF IUI Fertility Treatment in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Expert IUI and IVF guidance by Dr. Sanjana L at Health Nest, HSR Layout. Compassionate care for couples seeking fertility treatment in Bangalore.',
  },
  {
    slug: 'laparoscopic-surgery',
    title: 'Laparoscopic Gynaecology Surgery in Bangalore',
    shortTitle: 'Laparoscopic Surgery',
    description: 'Minimally invasive surgery for fibroids, cysts, endometriosis, and more.',
    icon: 'Scissors',
    category: 'Surgery',
    overview: 'Laparoscopic (keyhole) surgery is a minimally invasive surgical approach that allows Dr. Sanjana L to diagnose and treat a wide range of gynaecological conditions through tiny incisions. Compared to open surgery, laparoscopy means less pain, faster recovery, minimal scarring, and a quicker return to normal life. Dr. Sanjana is highly experienced in laparoscopic procedures for conditions including ovarian cysts, fibroids, endometriosis, tubal blockage, and more.',
    whatToExpect: [
      'Pre-operative consultation and investigations',
      'Anaesthesia (general anaesthesia) — procedure typically done as day surgery',
      'Small incisions (5–10mm) through which a camera and instruments are inserted',
      'Procedure time: 30 minutes to 2 hours depending on complexity',
      'Recovery in hospital: usually 1 day',
      'Return to normal activities: 1–2 weeks',
    ],
    whenToSeeDoctor: [
      'Persistent pelvic pain not responding to medication',
      'Suspected ovarian cysts or fibroids',
      'Diagnosis or treatment of endometriosis',
      'Blocked fallopian tubes affecting fertility',
      'Undiagnosed pelvic or abdominal pathology',
    ],
    whyChooseDrSanjana: [
      'Extensive experience in advanced laparoscopic gynaecological surgery',
      'Minimal scarring and fast recovery techniques',
      'Clear pre- and post-operative counselling',
      'High surgical precision with patient safety as the top priority',
    ],
    faqs: [
      { q: 'Is laparoscopic surgery safe?', a: 'Yes, laparoscopic surgery is generally very safe with a low complication rate compared to open surgery. Dr. Sanjana will discuss specific risks based on your procedure during your pre-operative consultation.' },
      { q: 'How long is recovery after laparoscopic surgery?', a: 'Most patients return to light activity within 3–5 days and full activity within 1–2 weeks. This is significantly faster than open surgery, which typically requires 4–6 weeks.' },
    ],
    relatedSlugs: ['hysteroscopy', 'pcos-pcod-treatment', 'fertility-treatment', 'menstrual-disorders'],
    metaTitle: 'Laparoscopic Gynaecology Surgery in Bangalore | Health Nest HSR Layout',
    metaDescription: 'Minimally invasive laparoscopic surgery for fibroids, ovarian cysts, endometriosis by Dr. Sanjana L at Health Nest, HSR Layout Bangalore.',
  },
  {
    slug: 'hysteroscopy',
    title: 'Hysteroscopy in HSR Layout Bangalore',
    shortTitle: 'Hysteroscopy',
    description: 'Diagnostic and operative hysteroscopy for uterine conditions.',
    icon: 'Search',
    category: 'Surgery',
    overview: 'Hysteroscopy is a procedure that allows Dr. Sanjana L to look inside the uterus using a thin, lighted telescope (hysteroscope) inserted through the cervix. It can be used for diagnosis (to investigate abnormal bleeding, recurrent miscarriage, or infertility) or for treatment (to remove polyps, fibroids, or uterine adhesions). It is minimally invasive, usually requires no incisions, and offers rapid recovery.',
    whatToExpect: [
      'Pre-procedure consultation and investigation',
      'Usually performed under local or general anaesthesia',
      'Procedure time: 15–45 minutes',
      'No external incisions — scope is inserted through the vagina',
      'Mild cramping post-procedure, resolving within 1–2 days',
      'Return to normal activities within 1–3 days',
    ],
    whenToSeeDoctor: [
      'Abnormal or heavy menstrual bleeding',
      'Suspected uterine polyps or submucosal fibroids',
      'Recurrent implantation failure after IVF',
      'Recurrent miscarriages',
      'Suspected uterine septum or abnormality',
    ],
    whyChooseDrSanjana: [
      'Experience in both diagnostic and operative hysteroscopy',
      'Comfortable, well-explained procedure with minimal discomfort',
      'Combines hysteroscopy with laparoscopy when needed',
      'Detailed post-procedure report and next steps guidance',
    ],
    faqs: [
      { q: 'Is hysteroscopy painful?', a: 'Most women experience mild cramping similar to period pain during or after the procedure. Adequate anaesthesia is used to minimise discomfort. Dr. Sanjana will explain all pain management options before the procedure.' },
      { q: 'How long after hysteroscopy can I become pregnant?', a: 'After an operative hysteroscopy (e.g., polyp or septum removal), most doctors recommend waiting 1–3 months before trying to conceive to allow the uterus to heal properly.' },
    ],
    relatedSlugs: ['laparoscopic-surgery', 'fertility-treatment', 'menstrual-disorders', 'ivf-iui'],
    metaTitle: 'Hysteroscopy in HSR Layout Bangalore | Health Nest - Dr. Sanjana L',
    metaDescription: 'Diagnostic and operative hysteroscopy for uterine polyps, fibroids, and unexplained infertility by Dr. Sanjana L at Health Nest, Bangalore.',
  },
  {
    slug: 'pcos-pcod-treatment',
    title: 'PCOS / PCOD Treatment in HSR Layout Bangalore',
    shortTitle: 'PCOS & PCOD Treatment',
    description: 'Effective hormonal management and lifestyle support for PCOS/PCOD.',
    icon: 'Activity',
    category: 'Gynaecology',
    overview: 'Polycystic Ovary Syndrome (PCOS) and Polycystic Ovarian Disease (PCOD) are among the most common hormonal disorders in women of reproductive age, affecting 1 in 5 Indian women. At Health Nest, Dr. Sanjana L provides evidence-based diagnosis, hormonal management, and lifestyle guidance to help you manage symptoms, regulate your cycle, protect long-term health, and achieve pregnancy if desired.',
    whatToExpect: [
      'Detailed hormonal and metabolic blood work (LH, FSH, testosterone, insulin)',
      'Pelvic ultrasound for ovarian morphology assessment',
      'Personalised treatment plan: lifestyle, medication, or both',
      'Menstrual cycle regulation with appropriate hormonal therapy',
      'Fertility support if pregnancy is desired',
      'Long-term follow-up to prevent complications (diabetes, cardiovascular disease)',
    ],
    whenToSeeDoctor: [
      'Irregular or absent periods',
      'Excessive hair growth (hirsutism) or hair loss',
      'Acne that is not responding to standard treatments',
      'Unexplained weight gain or difficulty losing weight',
      'Trouble conceiving',
    ],
    whyChooseDrSanjana: [
      'Holistic approach addressing both the hormonal and metabolic aspects of PCOS',
      'Diet and lifestyle counselling integrated with medical treatment',
      'Fertility support for women who want to conceive',
      'Long-term monitoring to protect against PCOS-related complications',
    ],
    faqs: [
      { q: 'What is the difference between PCOS and PCOD?', a: 'PCOD refers to a condition where ovaries produce many immature eggs, causing them to become cystic. PCOS is a more complex endocrine disorder with systemic metabolic effects. PCOS is considered more severe, though both are manageable with the right treatment.' },
      { q: 'Can PCOS be cured?', a: 'PCOS cannot be permanently cured, but its symptoms can be effectively managed with lifestyle changes, medication, and regular monitoring. Many women with PCOS live healthy lives and conceive successfully with appropriate treatment.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'fertility-treatment', 'adolescent-gynaecology', 'menopause-management'],
    metaTitle: 'PCOS PCOD Treatment in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Effective PCOS/PCOD diagnosis and treatment by Dr. Sanjana L. Hormonal management, lifestyle guidance & fertility support at Health Nest, HSR Layout.',
  },
  {
    slug: 'menstrual-disorders',
    title: 'Menstrual Disorders Treatment in Bangalore',
    shortTitle: 'Menstrual Disorders',
    description: 'Diagnosis and treatment for irregular, painful, or heavy periods.',
    icon: 'Calendar',
    category: 'Gynaecology',
    overview: 'Menstrual irregularities — whether heavy bleeding, painful periods, absent periods, or irregular cycles — can significantly impact your quality of life. These symptoms are often signs of underlying conditions that are highly treatable. At Health Nest, Dr. Sanjana L offers thorough evaluation and personalised treatment to restore comfortable, regular menstrual health.',
    whatToExpect: [
      'Detailed menstrual history and symptom assessment',
      'Blood tests (hormones, thyroid, anaemia screen)',
      'Pelvic ultrasound',
      'Hysteroscopy if abnormal uterine pathology is suspected',
      'Medical management with hormones, anti-inflammatories, or other medications',
      'Surgical management (hysteroscopy, laparoscopy) when required',
    ],
    whenToSeeDoctor: [
      'Periods lasting more than 7 days or saturating a pad every 1–2 hours',
      'Severe cramping that limits daily activities (dysmenorrhoea)',
      'No period for 3+ months (not due to pregnancy)',
      'Bleeding between periods or after intercourse',
      'Sudden changes in your normal menstrual pattern',
    ],
    whyChooseDrSanjana: [
      'Thorough evaluation to identify the root cause — not just manage symptoms',
      'Range of medical and surgical treatment options',
      'Sensitive, non-judgmental approach to intimate health concerns',
      'Long-term follow-up to ensure lasting improvement',
    ],
    faqs: [
      { q: 'What causes heavy periods?', a: 'Heavy periods (menorrhagia) can be caused by fibroids, polyps, adenomyosis, hormonal imbalances, thyroid disorders, or clotting problems. A thorough evaluation by Dr. Sanjana will identify the cause and guide appropriate treatment.' },
      { q: 'Are painful periods normal?', a: 'Mild cramping during periods is common, but severe pain that interferes with your daily life is not normal and should be evaluated. Conditions like endometriosis or adenomyosis are common causes of severe period pain.' },
    ],
    relatedSlugs: ['pcos-pcod-treatment', 'laparoscopic-surgery', 'hysteroscopy', 'menopause-management'],
    metaTitle: 'Menstrual Disorders Treatment in Bangalore | Health Nest HSR Layout',
    metaDescription: 'Diagnosis and treatment for irregular, heavy, or painful periods by Dr. Sanjana L at Health Nest, HSR Layout, Bangalore.',
  },
  {
    slug: 'menopause-management',
    title: 'Menopause Management in HSR Layout Bangalore',
    shortTitle: 'Menopause Management',
    description: 'Supportive care to help you navigate menopause comfortably and healthily.',
    icon: 'Sun',
    category: 'Gynaecology',
    overview: 'Menopause is a natural transition in every woman\'s life, but its symptoms — hot flushes, sleep disturbances, mood changes, and vaginal dryness — can significantly affect your wellbeing. Dr. Sanjana L at Health Nest provides comprehensive menopause care, offering everything from symptom management to long-term bone and cardiovascular health protection, helping you embrace this new chapter with confidence.',
    whatToExpect: [
      'Comprehensive menopausal assessment (symptoms, LMP, blood tests)',
      'Bone density assessment (DEXA scan referral if needed)',
      'Discussion of Hormone Replacement Therapy (HRT) — risks and benefits',
      'Non-hormonal alternatives for symptom management',
      'Cardiovascular and bone health guidance',
      'Ongoing monitoring and medication adjustment if on HRT',
    ],
    whenToSeeDoctor: [
      'Hot flushes and night sweats disrupting your sleep and daily life',
      'Vaginal dryness or pain during intercourse',
      'Mood swings, anxiety, or depression around the menopausal transition',
      'Irregular periods in your 40s or 50s',
      'Concerns about bone health or osteoporosis risk',
    ],
    whyChooseDrSanjana: [
      'Evidence-based menopause care tailored to your symptoms and health profile',
      'Open, comfortable conversations about intimate health concerns',
      'Balanced discussion of HRT benefits vs risks personalised to you',
      'Long-term wellness focus beyond just symptom relief',
    ],
    faqs: [
      { q: 'What is the average age of menopause in Indian women?', a: 'The average age of natural menopause in Indian women is around 46–47 years, slightly earlier than the global average of 51. Perimenopause (the transition phase) can begin several years before this.' },
      { q: 'Is Hormone Replacement Therapy (HRT) safe?', a: 'For most women under 60 who start HRT within 10 years of menopause, the benefits generally outweigh the risks. Dr. Sanjana will review your complete health history to determine if HRT is appropriate and safe for you.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'cervical-cancer-screening', 'urogynaecology', 'contraception-counselling'],
    metaTitle: 'Menopause Management in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Compassionate menopause care including HRT, symptom management and long-term health guidance by Dr. Sanjana L at Health Nest, Bangalore.',
  },
  {
    slug: 'prenatal-screening',
    title: 'Prenatal Screening in HSR Layout Bangalore',
    shortTitle: 'Prenatal Screening',
    description: 'Comprehensive antenatal tests for healthy fetal development.',
    icon: 'ScanLine',
    category: 'Obstetrics',
    overview: 'Prenatal screening helps detect potential chromosomal abnormalities, structural defects, and maternal health risks early in pregnancy so that appropriate management can be planned. At Health Nest, Dr. Sanjana L guides you through all recommended screening tests with clear explanations, helping you make informed decisions without unnecessary anxiety.',
    whatToExpect: [
      'First trimester combined screening (nuchal translucency scan + blood tests)',
      'Non-Invasive Prenatal Testing (NIPT) for chromosomal conditions',
      'Anomaly scan (morphology scan) at 18–22 weeks',
      'Glucose Tolerance Test (GTT) for gestational diabetes',
      'Growth scans in the third trimester',
      'Biophysical profile and Doppler studies if indicated',
    ],
    whenToSeeDoctor: [
      'As part of your routine early pregnancy care',
      'Family history of chromosomal conditions',
      'Advanced maternal age (35+ years)',
      'Previous pregnancy with a chromosomal or structural abnormality',
    ],
    whyChooseDrSanjana: [
      'Thorough counselling before and after screening tests',
      'Clear explanation of test results without causing unnecessary alarm',
      'Coordinated referral for further diagnostic tests if needed',
      'Supportive, non-directive approach to informed decision-making',
    ],
    faqs: [
      { q: 'Is prenatal screening mandatory?', a: 'Prenatal screening is not mandatory — it is your choice. Dr. Sanjana will explain each test, what it checks for, and what the results might mean, empowering you to decide what is right for you and your family.' },
      { q: 'What is the difference between screening and diagnostic tests?', a: 'Screening tests (like NIPT and anomaly scans) identify risks but are not definitive. If a screening test raises a concern, diagnostic tests like amniocentesis or chorionic villus sampling (CVS) can confirm the diagnosis.' },
    ],
    relatedSlugs: ['pregnancy-care', 'high-risk-pregnancy', 'postnatal-care', 'normal-delivery'],
    metaTitle: 'Prenatal Screening in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Comprehensive prenatal screening including anomaly scans, NIPT, and GTT guided by Dr. Sanjana L at Health Nest, HSR Layout, Bangalore.',
  },
  {
    slug: 'postnatal-care',
    title: 'Postnatal Care in HSR Layout Bangalore',
    shortTitle: 'Postnatal Care',
    description: 'Post-delivery recovery, breastfeeding support, and newborn care guidance.',
    icon: 'Heart',
    category: 'Obstetrics',
    overview: 'The weeks after delivery are a time of physical recovery, emotional adjustment, and new beginnings. Dr. Sanjana L provides comprehensive postnatal care to support your healing, address breastfeeding challenges, monitor your emotional wellbeing, and check your newborn\'s early health. You have brought a new life into the world — you deserve dedicated care now too.',
    whatToExpect: [
      'Postnatal review at 1–2 weeks post-delivery (wound, recovery)',
      '6-week comprehensive postnatal check (physical and emotional)',
      'Breastfeeding counselling and lactation support',
      'Contraception counselling for the postnatal period',
      'Screening for postnatal depression and anxiety',
      'Pelvic floor and physical recovery guidance',
    ],
    whenToSeeDoctor: [
      'Heavy postpartum bleeding beyond the first 10 days',
      'Signs of wound infection (redness, swelling, discharge)',
      'Persistent perineal or caesarean wound pain',
      'Feeling overwhelmed, persistently sad, or anxious (signs of postnatal depression)',
      'Difficulty breastfeeding or concerns about milk supply',
    ],
    whyChooseDrSanjana: [
      'Warm, comprehensive postnatal care beyond the standard 6-week check',
      'Postnatal depression screening and compassionate mental health support',
      'Breastfeeding guidance with practical, evidence-based advice',
      'Long-term follow-up to ensure your full recovery',
    ],
    faqs: [
      { q: 'When should I have my first postnatal check?', a: 'Your first review should ideally happen 1–2 weeks after delivery to check your recovery, then a comprehensive 6-week check. If you had a C-section, wound review is particularly important at 1–2 weeks.' },
      { q: 'What is postnatal depression?', a: 'Postnatal depression is a type of depression that affects some new mothers after delivery. Symptoms include persistent sadness, anxiety, feeling overwhelmed, and difficulty bonding with your baby. It is very common and very treatable — please do not hesitate to speak with Dr. Sanjana.' },
    ],
    relatedSlugs: ['pregnancy-care', 'normal-delivery', 'cesarean-delivery', 'prenatal-screening'],
    metaTitle: 'Postnatal Care in HSR Layout Bangalore | Health Nest - Dr. Sanjana L',
    metaDescription: 'Comprehensive postnatal care including recovery, breastfeeding support, and mental wellbeing by Dr. Sanjana L at Health Nest, HSR Layout.',
  },
  {
    slug: 'contraception-counselling',
    title: 'Contraception Counselling in Bangalore | Health Nest',
    shortTitle: 'Contraception Counselling',
    description: 'Personalised guidance on the right contraceptive method for your lifestyle.',
    icon: 'ShieldCheck',
    category: 'Gynaecology',
    overview: 'Choosing the right contraception is a deeply personal decision that depends on your health, lifestyle, relationship, and future family plans. Dr. Sanjana L at Health Nest offers non-judgmental, comprehensive counselling on all available contraceptive methods, helping you understand your options and make the choice that works best for you.',
    whatToExpect: [
      'Discussion of all contraceptive options: pills, patches, implant, IUD, injection, barrier methods',
      'Assessment of your health history and lifestyle to guide recommendations',
      'IUD (copper or hormonal) insertion if chosen',
      'Implant insertion if chosen',
      'Emergency contraception guidance',
      'Follow-up to review your chosen method and address any concerns',
    ],
    whenToSeeDoctor: [
      'Planning to delay or space pregnancies',
      'Unhappy with your current contraceptive method',
      'After delivery — planning postnatal contraception',
      'Perimenopausal contraception needs',
      'Questions about long-term contraceptive options',
    ],
    whyChooseDrSanjana: [
      'Non-judgmental, patient-led contraception counselling',
      'Experience with IUD and implant insertion procedures',
      'Up-to-date knowledge of all available contraceptive options',
      'Consideration of your complete health profile in recommendations',
    ],
    faqs: [
      { q: 'What is the most effective form of contraception?', a: 'Long-acting reversible contraceptives (LARCs) like hormonal IUDs (Mirena) and implants are the most effective (>99%). Oral contraceptive pills are 91–99% effective with typical use. Dr. Sanjana will help you find the best option for your lifestyle.' },
      { q: 'Is the copper IUD effective as emergency contraception?', a: 'Yes, the copper IUD is the most effective form of emergency contraception (>99%) when inserted within 5 days of unprotected intercourse, and provides ongoing long-term contraception.' },
    ],
    relatedSlugs: ['postnatal-care', 'menopause-management', 'adolescent-gynaecology', 'menstrual-disorders'],
    metaTitle: 'Contraception Counselling in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Expert, non-judgmental contraception counselling and IUD/implant insertion by Dr. Sanjana L at Health Nest, HSR Layout, Bangalore.',
  },
  {
    slug: 'cervical-cancer-screening',
    title: 'Cervical Cancer Screening in Bangalore | Health Nest',
    shortTitle: 'Cervical Cancer Screening',
    description: 'Pap smear and HPV testing for early detection and prevention.',
    icon: 'Shield',
    category: 'Gynaecology',
    overview: 'Cervical cancer is one of the most preventable cancers when detected early. Regular cervical screening — Pap smears and HPV testing — can identify abnormal cells before they develop into cancer. Dr. Sanjana L at Health Nest provides comfortable, expert cervical screening with clear follow-up guidance, empowering every woman to protect her health.',
    whatToExpect: [
      'Pap smear: a quick 2-minute procedure collecting cells from the cervix',
      'HPV testing: to detect high-risk HPV strains',
      'Results typically available within 1–2 weeks',
      'Colposcopy referral if abnormal results require further evaluation',
      'HPV vaccination guidance',
      'Screening reminder system to ensure regular follow-up',
    ],
    whenToSeeDoctor: [
      'All sexually active women from age 21 (or within 3 years of first intercourse)',
      'Bleeding after intercourse',
      'Unusual vaginal discharge',
      'Pelvic pain',
      'Due for routine 3-yearly screening',
    ],
    whyChooseDrSanjana: [
      'Comfortable, dignified screening experience with compassionate care',
      'Clear explanation of results and next steps',
      'Comprehensive screening combined with HPV testing',
      'Proactive HPV vaccination guidance',
    ],
    faqs: [
      { q: 'How often should women get a Pap smear?', a: 'Women aged 21–65 should have a Pap smear every 3 years. If combined with an HPV test (co-testing), screening can be every 5 years for women aged 30–65. Dr. Sanjana will recommend the schedule right for you.' },
      { q: 'Can I get a Pap smear during my period?', a: 'It is best to schedule your Pap smear when you are not menstruating, as blood can affect the results. Ideally, schedule it 10–20 days after the start of your last period.' },
    ],
    relatedSlugs: ['menstrual-disorders', 'adolescent-gynaecology', 'contraception-counselling', 'menopause-management'],
    metaTitle: 'Cervical Cancer Screening (Pap Smear) in Bangalore | Health Nest',
    metaDescription: 'Pap smear and HPV testing for cervical cancer screening by Dr. Sanjana L at Health Nest, HSR Layout, Bangalore. Protect your health today.',
  },
  {
    slug: 'urogynaecology',
    title: 'Urogynaecology Treatment in Bangalore | Health Nest',
    shortTitle: 'Urogynaecology',
    description: 'Treatment for urinary incontinence, pelvic organ prolapse, and bladder issues.',
    icon: 'Droplets',
    category: 'Gynaecology',
    overview: 'Urogynaecological problems — such as leaking urine when you laugh, cough, or sneeze, or the sensation of a bulge in the vagina — are far more common than many women realise, and far more treatable too. Dr. Sanjana L at Health Nest offers compassionate, expert urogynaecological assessment and treatment, helping women regain control of their bladder and pelvic health.',
    whatToExpect: [
      'Detailed urogynaecological history and symptom assessment',
      'Pelvic examination and prolapse assessment',
      'Urodynamic testing referral if needed',
      'Pelvic floor physiotherapy referral',
      'Medical management (medications, pessaries)',
      'Surgical management (prolapse repair, incontinence procedures) when indicated',
    ],
    whenToSeeDoctor: [
      'Leaking urine when coughing, sneezing, laughing, or exercising',
      'Urgently needing the toilet and not making it in time',
      'Feeling of fullness or pressure in the vagina',
      'Visible bulge at the vaginal opening',
      'Difficulty emptying your bladder fully',
    ],
    whyChooseDrSanjana: [
      'Compassionate care for often under-discussed pelvic health problems',
      'Range of conservative to surgical treatment options',
      'Integrated pelvic floor physiotherapy guidance',
      'Experience in prolapse assessment and surgical repair',
    ],
    faqs: [
      { q: 'Is urinary leakage normal after childbirth?', a: 'Urinary leakage after childbirth is common but not inevitable, and it should not simply be accepted as normal. With appropriate pelvic floor therapy and, if needed, medical or surgical treatment, it is very treatable.' },
    ],
    relatedSlugs: ['menopause-management', 'laparoscopic-surgery', 'postnatal-care', 'menstrual-disorders'],
    metaTitle: 'Urogynaecology Treatment in Bangalore | Health Nest HSR Layout',
    metaDescription: 'Expert urogynaecology care for urinary incontinence and pelvic organ prolapse by Dr. Sanjana L at Health Nest, HSR Layout, Bangalore.',
  },
  {
    slug: 'adolescent-gynaecology',
    title: 'Adolescent Gynaecology in HSR Layout Bangalore',
    shortTitle: 'Adolescent Gynaecology',
    description: 'Sensitive gynaecological care for young girls and teenagers.',
    icon: 'UserRound',
    category: 'Gynaecology',
    overview: 'Adolescent gynaecology addresses the unique health needs of young girls and teenagers — from puberty questions and menstrual concerns to reproductive health education. Dr. Sanjana L provides a safe, confidential, and non-judgmental environment where young women feel comfortable discussing their concerns, and parents receive thoughtful guidance on supporting their daughters\'s health.',
    whatToExpect: [
      'Discussion of puberty, menstrual health, and normalcy',
      'Evaluation and management of irregular or absent periods',
      'PCOS/PCOD diagnosis and management in teenagers',
      'HPV vaccination guidance',
      'Patient, age-appropriate reproductive health education',
      'Parental counselling where appropriate',
    ],
    whenToSeeDoctor: [
      'No periods by age 16 (primary amenorrhoea)',
      'Extremely painful periods limiting daily activities',
      'Irregular periods for more than 2 years after first period',
      'Unusual vaginal discharge or persistent lower abdominal pain',
      'Questions about puberty, reproductive health, or sexual health',
    ],
    whyChooseDrSanjana: [
      'Gentle, non-judgmental, age-appropriate consultations',
      'Confidential consultations with teenage patients (with parental discretion)',
      'Multi-lingual capability to communicate comfortably',
      'Experience diagnosing PCOS and hormonal conditions in adolescents',
    ],
    faqs: [
      { q: 'At what age should a girl have her first gynaecological appointment?', a: 'The first gynaecological visit is recommended between ages 13–15, not necessarily for an internal exam, but for education, relationship building, and addressing any menstrual concerns. Earlier if there are specific issues.' },
    ],
    relatedSlugs: ['pcos-pcod-treatment', 'menstrual-disorders', 'cervical-cancer-screening', 'contraception-counselling'],
    metaTitle: 'Adolescent Gynaecology in HSR Layout Bangalore | Health Nest',
    metaDescription: 'Sensitive, compassionate gynaecological care for teenagers and young women by Dr. Sanjana L at Health Nest, HSR Layout, Bangalore.',
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(s => s.slug === slug);
}

export function getRelatedServices(slugs: string[]): Service[] {
  return slugs.map(s => services.find(svc => svc.slug === s)).filter(Boolean) as Service[];
}

export const serviceCategories = ['Obstetrics', 'Fertility', 'Surgery', 'Gynaecology'];
